### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by iamAdrianIusca**
- removed the directx searching from the main cmake file, is already searched in the assimp tool and samples folders
- remove the unnecessary const
- .clear in destructor is redundant for std container
- small improvements

### CODE REVIEW

**Comment by turol** [comment]
`std::make_unique` requires C++14. This project is still C++11.

**Comment by iamAdrianIusca** [comment]
@turol you are right. I will change it in a new commit.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by iamAdrianIusca** [comment]
your welcome

**Pull request merged**
