### PR TITLE
Added tests to C API missing functionalities in #3091

### PR DESCRIPTION
**Pull request by malortie**
[Link to issue](https://github.com/assimp/assimp/issues/3091).

List of changes:

- Changed randomized math structure values to predefined values to prevent cases that could potentially lead to division by zero (**1**)
- Removed unused variable(s) due to (**1**)
- Renamed variable(s) for better clarity

These changes were tested on 32 bits and 64 bits builds.

### CODE REVIEW

**Comment by malortie** [comment]
The build on mac failed with the following error:

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: random_device got EOF: No message available on STREAM
/Users/runner/runners/2.168.0/work/_temp/1796b1cc-755f-4dbb-89a2-56864c3edaa8.sh: line 1:  2530 Abort trap: 6           ./unit
##[error]Process completed with exit code 134.
```

**Comment by kimkulling** [comment]
Looks good, I just added the documentation for the public math-tools.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by malortie** [comment]
@kimkulling My apologies for the amount of fixes that were required. Thanks again.

**Pull request merged**
