### PR TITLE
fix issue #5461 (segfault after removing redundant materials)

### PR DESCRIPTION
**Pull request by stephengold**
Update `mNumMaterials` before early return from `RemoveRedundantMatsProcess::Execute()` .

### CODE REVIEW

**Comment by stephengold** [comment]
I tested this fix on the "Running.gltf" model from issue #5461 and verified that the command completes successfully:  no segfault.
I believe this pull request solves #5461 (without introducing any new issues) and is ready to be integrated.

**Comment by kimkulling** [comment]
During the review I have detected 2 leaks.

**Comment by stephengold** [comment]
@kimkulling Thanks for solving the memory leaks.

**Comment by kimkulling** [comment]
Hm, tests are failing for g++ on Ubuntu. I cannot reproduce it on windows. I will try to analyze it with Linux.

**Comment by stephengold** [comment]
I tried to reproduce the test failure on my Linux desktop and was unsuccessful:  all 574 tests passed.
My desktop used GNU 11.4.0, just like the GHA runner.

**Comment by stephengold** [comment]
It seems my merge solved the test failure!
I believe this PR is now ready for integration.

**Comment by stephengold** [comment]
After another merge from 'master', the tests are failing again.

**Comment by stephengold** [comment]
Once again, merging has solved the failing checks. Please integrate this PR.

**Comment by stephengold** [comment]
After another merge from 'master', another failing check.
I see no alternative except to wait for another merge opportunity.

**Comment by stephengold** [comment]
Once again, merging has solved the failing checks. @kimkulling please integrate this PR.

**Comment by kimkulling** [comment]
Updated again, let's hope that the tests are green.

**Pull request merged**
