### PR TITLE
Added test case for fix earlier submitted

### PR DESCRIPTION
**Pull request by ms-maxvollmer**
Added test file and test case for ASCII FBX files with invalid (out of bounds) float values

### CODE REVIEW

**Comment by ms-maxvollmer** [comment]
@kimkulling Is that failed Travis CI build due to some issue on your side of things? I checked the logs and couldn't see how the errors are related to the changes in the PR, but I might be mistaken of course.

**Comment by kimkulling** [comment]
I have to check, ath the moment I am pretty busy with the children staying at home ... So sorry for the delays :-).

**Comment by ms-maxvollmer** [comment]
No worries! It took me almost a month to deliver this unit test, so really, no rush :D Stay safe :)

**Comment by kimkulling** [comment]
It was just an error of the image-startup.

**Comment by kimkulling** [comment]
Mergd, thanks a lot for your contribution. And take care!!!

**Pull request merged**
