### PR TITLE
Asan

### PR DESCRIPTION
**Pull request by turol**
Add AddressSanitizer support, fix one of the bugs and enable it on Travis. I've just enabled this as part of the clang config, should we make it a separate configuration? AddressSanitizer should also work on mac, do we want to enable it there?

Expecting this to fail initially since at least one unit test is not clean. It seems to be misusing MaterialSystem AddProperty. Not sure what exactly is wrong and the test is 9 years old.

### CODE REVIEW

**Comment by turol** [comment]
Looks like it needs some rethinking because MSVC doesn't understand shared_ptr to an array.

**Comment by dhritzkiv** [comment]
Could this work: 

```h
#if _MSC_VER
#shared_ptr<uint8_t> mData; //!< Pointer to the data
#    else
#shared_ptr<uint8_t[] > mData; //!< Pointer to the data
#endif
```

**Comment by turol** [comment]
That won't work, older GCC doesn't understand it either.

**Comment by turol** [comment]
Ok, now I got the expected failure. Unfortunately it looks like Travis doesn't have debug symbols enabled so there's no source code locations in that backtrace. Should I enable them for that configuration?

Here's a symbolized backtrace from my computer:

```
ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffe73830d0 at pc 0x0000005d06e5 bp 0x7fffe7382df0 sp 0x7fffe73825a0
READ of size 64 at 0x7fffe73830d0 thread T0
    #0 0x5d06e4 in __asan_memcpy (assimp/asan/test/unit+0x5d06e4)
    #1 0x8f093c in aiMaterial::AddBinaryProperty(void const*, unsigned int, char const*, unsigned int, unsigned int, aiPropertyTypeInfo) assimp/code/MaterialSystem.cpp:485:5
    #2 0x73611c in aiReturn aiMaterial::AddProperty<float [4]>(float const (*) [4], unsigned int, char const*, unsigned int, unsigned int) assimp/include/assimp/material.inl:200:12
    #3 0x73300f in MaterialSystemTest_testFloatArrayProperty_Test::TestBody() assimp/test/unit/utMaterialSystem.cpp:76:5
    #4 0x6a074b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #5 0x666be0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #6 0x6328d9 in testing::Test::Run() assimp/test/../contrib/gtest/src/gtest.cc:2474:5
    #7 0x634571 in testing::TestInfo::Run() assimp/test/../contrib/gtest/src/gtest.cc:2656:5
    #8 0x6355c1 in testing::TestCase::Run() assimp/test/../contrib/gtest/src/gtest.cc:2774:5
    #9 0x6445dc in testing::internal::UnitTestImpl::RunAllTests() assimp/test/../contrib/gtest/src/gtest.cc:4649:11
    #10 0x6ac9e6 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #11 0x66c1a0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #12 0x643bf6 in testing::UnitTest::Run() assimp/test/../contrib/gtest/src/gtest.cc:4257:10
    #13 0x6b84f0 in RUN_ALL_TESTS() assimp/test/../contrib/gtest/include/gtest/gtest.h:2233:10
    #14 0x6b83a8 in main assimp/test/unit/Main.cpp:26:18
    #15 0x7fed630f52e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #16 0x548419 in _start (assimp/asan/test/unit+0x548419)

Address 0x7fffe73830d0 is located in stack of thread T0 at offset 48 in frame
    #0 0x732c9f in MaterialSystemTest_testFloatArrayProperty_Test::TestBody() assimp/test/unit/utMaterialSystem.cpp:73

  This frame has 16 object(s):
    [32, 48) 'pf'
    [64, 68) 'pMax' <== Memory access at offset 48 partially underflows this variable
    [80, 96) 'gtest_ar' <== Memory access at offset 48 partially underflows this variable
    [112, 116) ''
    [128, 132) ''
    [144, 152) ''
    [176, 184) ''
    [208, 224) 'gtest_ar1'
    [240, 248) ''
    [272, 280) ''
    [304, 312) ''
    [336, 352) 'gtest_ar_'
    [368, 369) ''
    [384, 392) ''
    [416, 448) ''
    [480, 488) ''
```

[`aiMaterial::AddBinaryProperty`](https://github.com/assimp/assimp/blob/master/code/MaterialSystem.cpp#L485) is reading too much data from a buffer declared on [`MaterialSystemTest_testFloatArrayProperty_Test::TestBody`](https://github.com/assimp/assimp/blob/master/test/unit/utMaterialSystem.cpp#L76) stack. This code looks wrong, `pf` is already a pointer because it's an array. Taking its address can't possibly result in anything sane. `TestIntArrayProperty` probably has the same bug. Why does this unit test pass?

@acgessler git blames you for this code.

**Comment by kimkulling** [comment]
Greate, we can enable the adress-sanitizer for one special build in our build matrix. There we can also enable a debug build to get the names in the call-stack. I will try to merge it and add a configuration for the check as well.

**Comment by turol** [comment]
@kimkulling This is not the only failure in unit test with AddressSanitizer, be careful about what you merge.

**Comment by kimkulling** [comment]
I will merge it and start fixing the issues. Great work, thanks a lot!

**Comment by kimkulling** [comment]
We do not need to put this as an array, you are right.

**Pull request merged**
