### PR TITLE
Check input token length before copy

### PR DESCRIPTION
**Pull request by ms-maxvollmer**
In ParseTokenAsFloat: Added check if length of input token is actually within expected range before copying the token into buffer. If length is too big, ignore the input and simply return 0.

### CODE REVIEW

**Comment by turol** [comment]
Can you add a unit test for this?

**Comment by turol** [comment]
If we ever hit this the model is probably corrupt. Would it be better to throw an exception instead?

**Comment by ms-maxvollmer** [comment]
The file that caused us to find this issue is an internal model file we fuzzed, so I can't publish that. I'll try to recreate a test case from a model file I can share.

An exception is fine as well. The important bit is that the check is there. Let me know if you want me to change it to throw an exception.

**Comment by turol** [comment]
Did you use AFL? You could try if its testcase minimification tool makes the file sufficiently unrecognizable to be included.

I'd prefer an exception from a corrupt model rather than appearing to load it but producing incorrect results. @kimkulling your opinion?

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
