### PR TITLE
[pyassimp] Bumped to 4.1.4

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Main changes:
- Support for metadata fields (Vincent Fazio, Wojciech Matyjewicz)
- added support for aiExportSceneToBlob (Vincent Fazio)
- a few bug fix + code beautification

The pip package has been updated accordingly.

### CODE REVIEW

**Comment by kimkulling** [comment]
Hi, are any commits missing? The only change I saw was the version stuff. The rest seems to be missing. 
And thanks a lot for the contribution.

Kim

**Comment by severin-lemaignan** [comment]
Hi @kimkulling
The PR was indeed only for the version bump -- I've released a new version of pyassimp on pip with the changes of the last months, and I needed to bumped the version number for that.

Thanks for merging it!

**Comment by wangg12** [comment]
Version 4.1.4 causes segmentation faults. I've tested on many linux machines, both the pip version and the master version fail. Is there any fixes?

**Comment by kimkulling** [comment]
Which kind of segfaults have you saw?

**Comment by wangg12** [comment]
The programs just craches with segmentation fault when loading meshes. @kimkulling

**Pull request merged**
