### PR TITLE
Gltf2 Sparse Accessor Export (blendshape export using sparse accessor)

### PR DESCRIPTION
**Pull request by thomasbiang**
This pr supports export gltf2 with sparse accessor. Particularly for exporting blendshapes using sparse accessor, it save many space.
It solves issue#2359: #2359

Sparse data structure is defined pull request: https://github.com/assimp/assimp/pull/3219, where pr 3219 imports sparse accessor and this pr exports sparse accessor.

This pr is tested with gltf2 from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube
I exported it using sparse blendshapes, it is correct and successfully being parsed by a 3rd party gltf2 viewer https://gltf-viewer.donmccurdy.com/.  It is tested with pr 3219 as well. Gltf2 exported using this pr can be successfully imported into assimp using pr 3219.

### CODE REVIEW

**Comment by thomasbiang** [comment]
Hi @kimkulling ,
How's the merging progress for this pr? I find there are many build failure reports across all the prs. I am wondering if I need to do anything for my case. Let me know.

**Comment by thomasbiang** [comment]
@kimkulling  Hi, the build and tests are all green and ready for being merged now.

**Comment by rbsheth** [comment]
Hi @kimkulling, any thoughts on this one? Patiently waiting on this for our workflow 🙏

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
