### PR TITLE
Fix implicit conversion errors on macOS

### PR DESCRIPTION
**Pull request by aaronmjacobs**
These changes fix 'Implicit conversion loses integer precision' errors by explicitly casting to the desired type. I am currently running Apple clang version 14.0.0 (clang-1400.0.29.202) on macOS 13.2.1 (22D68).

### CODE REVIEW

**Comment by turol** [comment]
This might cause warnings from MSVC about potential loss of data since you're casting to a smaller type.

You should use C++ style casts instead of C -style casts.

**Comment by aaronmjacobs** [comment]
I've updated the casts to be C++ style (except for miniz, since that is a C library).

I'm not sure I understand the concerns about warnings in MSVC. I would expect this to remove warnings (if there are any), as it is converting the casts from being implicit to explicit.

**Review by kimkulling — APPROVED** [review]
Looks fine. I am wondering why other compilers haven't found these things before.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
