### PR TITLE
Update tinyusdz

### PR DESCRIPTION
**Pull request by tellypresence**
Update 3rd party project `tinyusdz`
 - Update git commit
 - Update patch file
 - Remove unused var in PR #5812

### CODE REVIEW

**Comment by AMZN-Gene** [comment]
Tested this locally and it works; I only have to iterate one tiny USD skeleton, instead of one per sub-mesh, in order to discover bones. Thank you.
I'd give this PR an approval, but I don't have review permissions :)

**Review by AMZN-Gene — APPROVED** [review]

**Review by moudgils — APPROVED** [review]

**Comment by AMZN-Gene** [comment]
Hoping @kimkulling could take a look at this...

**Review by kimkulling — APPROVED** [review]
Looks fine.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
