### PR TITLE
FBX: Fix for loading taking a very long time on models with duplicate names

### PR DESCRIPTION
**Pull request by mlavik1**
My suggested fix for https://github.com/assimp/assimp/issues/2390

### CODE REVIEW

**Comment by mlavik1** [comment]
Closing the PR, as it has one issue (see comments [here](https://github.com/assimp/assimp/issues/2390)).
I'll make a new PR when I'm done with my changes.

**Comment by mlavik1** [comment]
Reopened: In the edge case of models containing both a node called "nodename001" (or another number) as well as a node called "nodename" we still generate valid names. I also replaced the _std::set_ with a _std::unordered_set_.

**Comment by mlavik1** [comment]
Sorry, I added the "typedef" back. I'll fix that at once.

**Comment by kimkulling** [comment]
Looks good for me.

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Comment by mlavik1** [comment]
@kimkulling I think you can close https://github.com/assimp/assimp/issues/2390 then :)

**Pull request merged**
