### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by smalcom**
gcc: 8.3.0
Built with: "-DASSIMP_COVERALLS:BOOL=ON -DASSIMP_WERROR:BOOL=ON"

### CODE REVIEW

**Comment by turol** [comment]
Casting to `void *` just hides the issue. Either fix it correctly (by not using `memcpy`) or detect the compiler version and silence the warning.

**Comment by smalcom** [comment]
> Casting to void *
But
man memcpy:
> void *memcpy(void *dest, const void *src, size_t n);


> detect the compiler version and silence the warning.
I think its a bad idea; step to macrohell.

**Comment by turol** [comment]
Yes, it's theoretically correct to cast to `void *` but that doesn't fix the problem, only hides it. If someone actually wants to fix it later they're going have to find and undo your changes before they can do it.

And checking the compiler doesn't take any macros in this case, it's purely a CMake thing. Check if the compiler supports '-Wno-class-memaccess' and turn it on if it does, then file an issue so it's not forgotten.

**Comment by smalcom** [comment]
Understood.

**Pull request closed without merging**
