### PR TITLE
Fix fuzzer crashes

### LINKED ISSUE #4222: Bug:Issue 38947 in oss-fuzz: assimp:assimp_fuzzer: Stack-buffer-overflow in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
Status: New
Owner: ----
CC: kim.k...@googlemail.com 
Labels: Restrict-View-Commit ClusterFuzz Stability-Memory-AddressSanitizer Reproducible OS-Linux Engine-afl Security_Severity-Medium Proj-assimp Reported-2021-09-18
Type: Bug-Security

New issue 38947 by ClusterFuzz-External: assimp:assimp_fuzzer: Stack-buffer-overflow in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38947

Detailed Report: https://oss-fuzz.com/testcase?key=4525389854670848

Project: assimp
Fuzzing Engine: afl
Fuzz Target: assimp_fuzzer
Job Type: afl_asan_assimp
Platform Id: linux

Crash Type: Stack-buffer-overflow READ 8
Crash Address: 0x7fcc428b69b0
Crash State:
  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
  
Sanitizer: address (ASAN)

Recommended Security Severity: Medium

Crash Revision: https://oss-fuzz.com/revisions?job=afl_asan_assimp&revision=202008080609

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=4525389854670848

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public.

### LINKED ISSUE #4228: Bug: Issue 38870 in oss-fuzz: assimp:assimp_fuzzer: Stack-buffer-overflow in Assimp::ZipArchiveIOSystem::Implement::MapArchive
Status: New
Owner: ----
CC: kim.k...@googlemail.com 
Labels: Restrict-View-Commit ClusterFuzz Stability-Memory-AddressSanitizer Reproducible Engine-libfuzzer OS-Linux Security_Severity-Medium Proj-assimp Reported-2021-09-17
Type: Bug-Security

New issue 38870 by ClusterFuzz-External: assimp:assimp_fuzzer: Stack-buffer-overflow in Assimp::ZipArchiveIOSystem::Implement::MapArchive
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38870

Detailed Report: https://oss-fuzz.com/testcase?key=6284280301486080

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_asan_assimp
Platform Id: linux

Crash Type: Stack-buffer-overflow READ {*}
Crash Address: 0x7f5dc50a3120
Crash State:
  Assimp::ZipArchiveIOSystem::Implement::MapArchive
  Assimp::ZipArchiveIOSystem::getFileList
  Assimp::D3MF::D3MFOpcPackage::D3MFOpcPackage
  
Sanitizer: address (ASAN)

Recommended Security Severity: Medium

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_assimp&range=202109150603:202109160613

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6284280301486080

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

### LINKED ISSUE #4229: Bug: Issue 38873 in oss-fuzz: assimp:assimp_fuzzer: Null-dereference READ in unzOpenCurrentFile3
Status: New
Owner: ----
CC: kim.k...@googlemail.com 
Labels: Restrict-View-Commit ClusterFuzz Stability-Memory-AddressSanitizer Reproducible Engine-libfuzzer OS-Linux Security_Severity-High Proj-assimp Reported-2021-09-17
Type: Bug-Security

New issue 38873 by ClusterFuzz-External: assimp:assimp_fuzzer: Null-dereference READ in unzOpenCurrentFile3
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38873

Detailed Report: https://oss-fuzz.com/testcase?key=5431707080196096

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_asan_assimp
Platform Id: linux

Crash Type: Null-dereference READ
Crash Address: 0x000000000000
Crash State:
  unzOpenCurrentFile3
  unzOpenCurrentFile
  Assimp::ZipFileInfo::Extract
  
Sanitizer: address (ASAN)

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_assimp&range=202109150603:202109160613

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5431707080196096

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

### PR DESCRIPTION
**Pull request by alpire**
This PR addresses [all but one of the OSS-Fuzz issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=proj&q=Type%3DBug-Security%20label%3ADeadline-Exceeded%20-label%3AStability-UndefinedBehaviorSanitizer%20label%3Areproducible%20proj%3Aassimp&can=2) marked as security relevant.

Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38947 (Fix #4222)
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38870 (Fix #4228)
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38873 (Fix #4229)

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Great work, thanks a lot for you contribution.

**Comment by krop** [comment]
The assimp 5.1.6 build fails on openSUSE:

```
[   33s] /home/abuild/rpmbuild/BUILD/assimp-5.1.6/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
[   33s] /home/abuild/rpmbuild/BUILD/assimp-5.1.6/code/Common/ZipArchiveIOSystem.cpp:199:13: error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'; did you mean 'zopen_file'?
[   33s]   199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
[   33s]       |             ^~~~~~~~~~~~~~
[   33s]       |             zopen_file
[   33s] /home/abuild/rpmbuild/BUILD/assimp-5.1.6/code/Common/ZipArchiveIOSystem.cpp:199:31: error: 'opendisk_file_func' was not declared in this scope; did you mean 'open_file_func'?
[   33s]   199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
[   33s]       |                               ^~~~~~~~~~~~~~~~~~
[   33s]       |                               open_file_func

```

**Comment by alpire** [comment]
Thanks for letting me know @krop. Wrapping the problematic line with a `#ifdef ZOPENDISK64` should handle multiple ioapi implementations (so that it works with contrib/unzip/ioapi.h as well as zlib).

@kimkulling: if that makes sense to you, I'd be happy to create the PR.

**Comment by mahiuchun** [comment]
@alpire Do you happen to know the origin of `zopendisk_file` addition?

I found https://github.com/hunter-packages/minizip/commit/6d35b6b8845fae3d3cbde67bdad40e47e4623cf8 and https://github.com/assimp/assimp/commit/54be7ac582599df9f32503ed435b65911a6ebc8b but I couldn't find corresponding upstream changes.

For example, https://github.com/madler/zlib/blob/master/contrib/minizip/ioapi.h does not have the function.

**Comment by alpire** [comment]
As you found out, it looks like `zopendisk_file` was added in https://github.com/assimp/assimp/pull/3556, which pulled changes from https://github.com/hunter-packages/minizip. That repo itself is an old fork of [minizip-ng](https://github.com/zlib-ng/minizip-ng).  [minizip-ng](https://github.com/zlib-ng/minizip-ng) removed `zopendisk_file` in [2017](https://github.com/zlib-ng/minizip-ng/commit/94611f11d4af76f7a685e82580abef107c4467cf).

**Pull request merged**
