### PR TITLE
Simplified file detection and fixed a few bugs

### PR DESCRIPTION
**Pull request by krishty**
The search for a matching importer had a few issues, see #3791. There were two different mechanisms to determine whether an importer accepts a specific file extension:
1. `aiImporterDesc::mFileExtensions`, which was forwarded to the UI via `BaseImporter::GetExtensionList()`.
2. `BaseImporter::CanRead()` when called with `checkSig == false`, which determines whether to actually use that importer.

They were redundant and got out of sync repeatedly. I removed 2. completely and replaced it with 1., thereby syncing UI/import and shortening all `BaseImporter::CanRead()` implementations.

Further bugfixes:
- fixed glTF2 importer throwing exceptions when checking whether it can load a file
- removed `BaseImporter::SimpleExtensionCheck()` because it is no longer used and had a bug with case sensitivity

Since the `checkSig` parameter in `BaseImporter::CanRead()` is now useless, it can be removed completely. I’m not sure if this would break ABI compatiblity, so I’ll submit it with a later pull request.

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Cool approach, thank you very much for the great contribution. CI is on its way.

**Comment by krishty** [comment]
Wow, sorry for the trouble!

Your first correction is right: Indeed, Microsoft’s STL seems to define `std::size()` in _any_ STL header, while libstd & Co. are more strict and only define it in a few selected headers. The additional `#include <iterator>` in `BaseImporter.h` is a good idea.

I don’t understand why it’s still failing. Did I rely on the wrong C++ standard? If this all falls apart, I’ll revert to hard-coded array sizes.

**Comment by krishty** [comment]
Plan B:
`BaseImporter.h`
`+ #define AI_COUNT_OF(X) (sizeof(X) / sizeof((X)[0]))`
… replace all `std::size(` with `AI_COUNT_OF(`.

**Comment by krishty** [comment]
@kimkulling here’s the fix I suggested above.

Unfortunately, two unit tests break and I’m sure it’s the test’s fault. Here’s what happens:
1. `glTF2Importer::CanRead()` did not catch any exceptions. This was an error for obvious reasons.
2. I fixed that; it now returns `false` a.k.a. “cannot read file” if an exception is thrown.
3. The test `utglTF2ImportExport.error_string_preserved` provides a file with a intentionally missing external reference. It is expected that the GLTF2 importer tries to load the file, notices the missing reference, and returns a valid error description (this is a good test).
4. When an importer for the test file is searched, `glTF2Importer::CanRead()` is called.
5. `CanRead()` loads the entire file. *I think this is trying too hard.*
6. While loading the entire file, it notices the missing reference and throws `GLTF: could not open referenced file "BoxTextured0.bin"`.
7. The exception is caught and translated to “GLTF2 importer cannot read this file”.
8. Since the GLTF2 importer cannot read this file, and no other importer can either, loading is aborted: No importer found.
9. The test fails.

Why did it work before? Since probing the file during `CanRead()` threw `GLTF: could not open referenced file "BoxTextured0.bin"` and `CanRead()` didn’t catch the exception, Assimp reported the correct error by accident, without even having determined the correct importer!

In order to pass the tests, it is required that GLTF2 only takes a quick look at the file during `CanRead()`, not loading it entirely and throwing detailed errors far in. I’m afraid I can’t provide that at this point because I’m not deep enough inside GLTF’s implementation.

So we must decide whether to
1. retire this pull request, or
2. disable the test;

… until `glTF2Importer::CanRead()` is less strict.

**Comment by Garux** [comment]
> I don’t understand why it’s still failing. Did I rely on the wrong C++ standard? If this all falls apart, I’ll revert to hard-coded array sizes.

std::size() is C++17 https://en.cppreference.com/w/cpp/iterator/size

**Comment by krishty** [comment]
@Garux Indeed, but that’s been worked around. The remaining blocking problem is the two broken unit tests.

**Comment by Garux** [comment]
Mentioning this, as C++17 gonna be available soon, it seems.

**Comment by krishty** [comment]
Very cool! Hit me up when it’s available and I’ll retrofit it by replacing `AI_COUNT_OF()` with `std::size`.

**Comment by kimkulling** [comment]
Merge will be done here: https://github.com/assimp/assimp/pull/4342

**Pull request closed without merging**
