### PR TITLE
[Collada] export <library_animations> tag

### PR DESCRIPTION
**Pull request by eevictor**
My project needs to save animations using collada format.  So, I have made changes to the ColladaExporter class to simply output the <library_animations> tag.  It is working fine for simple animation.  Hope this could contribute back to the community.

Assimp project rocks ! Thanks to dev team !

### CODE REVIEW

**Comment by dhritzkiv** [comment]
Hi @eevictor! You may want to fix up the [failing linux tests](https://travis-ci.org/assimp/assimp/jobs/290788887) before this PR is reviewed.

**Comment by dhritzkiv** [comment]
Fixes: #1510

**Comment by kimkulling** [comment]
there is a unsigned int / int mismatch which needs to get fixed.

**Comment by kimkulling** [comment]
Finally merged, thanks for the contribution!

**Comment by eevictor** [comment]
It's my honour to contribute.  Your team's effort in making out ASSIMP for
community uses is a genuine great deed for us to thank for.

Keep up the good work, thanks !

**Pull request merged**
