### PR TITLE
Handle gcs cloud storage file extensions with versioning.

### PR DESCRIPTION
**Pull request by feuerste**
If a user uses its own `IOSystem`/`IOStream` for handling google cloud storage uris, with this PR the extension will still be correct. Together with #5157 the following will be supported without going over all possible importers and trying to detect the format:
```
Assimp::Importer importer;
importer.SetIOHandler(new GsIOSystem(...));
const aiScene* scene = importer.ReadFile("gs://bucket/model.glb#1234", ...);
...
```

### CODE REVIEW

**Comment by turol** [comment]
I'm not sure this is a good idea. `#` is technically a valid character in file names so this might break something for someone.

**Comment by feuerste** [comment]
> I'm not sure this is a good idea. `#` is technically a valid character in file names so this might break something for someone.

Thanks @turol I agree that `#` is a valid file name character.
However, in this case we are explicitly looking at file extensions, and looking through https://en.wikipedia.org/wiki/List_of_file_formats reveals no single extension having a `#` inside. Furthermore, s3 and gcs regularly add their file versions behind the extension (and marking them with `#`), so it would be really useful for everyone extending `IOSystem`/`IOStream` with s3/gcs support to already detect the corresponding files based on their extension (see also #5157 in combination with this PR) and not having to wait for the loop going over all files, opening them, reading magic bytes or other ways to unify files.

**Comment by feuerste** [comment]
@kimkulling This PR depends on #5157. Once the other one is merged, I will update this one and let you know.

**Comment by turol** [comment]
I haven't used C++ regex but have heard many people (even on the committee) call it bad. We probably don't want to use it.

**Comment by feuerste** [comment]
> I haven't used C++ regex but have heard many people (even on the committee) call it bad. We probably don't want to use it.

Fine with me, too.

**Comment by feuerste** [comment]
@kimkulling This one is ready for review now as well :)

**Comment by kimkulling** [comment]
Just working on it.

**Comment by kimkulling** [comment]
If I get it right hashes will only get filtered out when they re part of the extension. So for me this looks fine. Some unittests would be great to have.

**Comment by feuerste** [comment]
> If I get it right hashes will only get filtered out when they re part of the extension. So for me this looks fine. Some unittests would be great to have.

Yes, this is correct. I added a few unit tests as well. PTAL!

**Review by kimkulling — APPROVED** [review]
Looks fine to me.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
