### PR TITLE
Stop JoinVerticiesProcess removing bones from mesh as per #2596

### PR DESCRIPTION
**Pull request by RevoluPowered**
Co-authored-by: K. S. Ernest (iFire) Lee <ernest.lee@chibifire.com>

### CODE REVIEW

**Comment by RevoluPowered** [comment]
Resolves #2596

**Comment by RevoluPowered** [comment]
@kimkulling can this be merged - are you okay with this change?

**Comment by kimkulling** [comment]
Good idea!

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Pull request merged**
