### PR TITLE
[RFC] cmake: targets: check lib or lib64 path

### PR DESCRIPTION
**Pull request by maquefel**
Linkage against lib or lib64 should be taken into assumption.

Without it we get:

The imported target "assimp::assimp" references the file

     "/usr/lib/libassimp.so.5"

When compiling against x86_64 target. The library of couse exits in
/usr/lib64.

see:
https://cmake.org/cmake/help/v3.17/prop_gbl/FIND_LIBRARY_USE_LIB64_PATHS.html

As i am not a master of cmake this should be double checked if
it doesn't break anything.

Signed-off-by: Nikita Shubin <NShubin@topcon.com>

### CODE REVIEW

**Comment by maquefel** [comment]
Might be related to https://github.com/assimp/assimp/issues/2719

**Comment by vmatare** [comment]
> When compiling against x86_64 target. The library of couse exits in
> /usr/lib64.
> 
> see:
> https://cmake.org/cmake/help/v3.17/prop_gbl/FIND_LIBRARY_USE_LIB64_PATHS.html

It is stated nowhere that libs always live in `/usr/lib64` on a 64-bit system. In fact, the FHS makes pretty explicit the fact that this is "commonly used", but in no way part of the standard: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s10.html

**Comment by umlaeute** [comment]
esp. Debian based systems (Ubuntu, Mint,...) use a [multi-arch approach](https://wiki.debian.org/Multiarch) that goes way beyond supporting a "32bit and 64bit variants of the same CPU" and does not use the `lib64/` folders

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by vmatare** [comment]
@kimkulling I don't think merging this was a good idea. Just guessing that libs will be in `lib64` is plain wrong, as I've stated before and others have confirmed. The whole stuff is not just superseded by #3115, but also incompatible, in that it uses variables that aren't defined any more. That is something that should have been visible in the merge conflicts in https://github.com/assimp/assimp/pull/3035/commits/2d4eab6db087d67726da46d2bf2b4ef1cbf2b501

**Pull request merged**
