### PR TITLE
Reinstate a deprecated gltfpbr macro: AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS

### PR DESCRIPTION
**Pull request by RichardTea**
Qt5 and Qt6.2.1 are also reading AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS in order to decide whether to read AI_MATKEY_GLTF_PBRSPECULARGLOSSINESS_GLOSSINESS_FACTOR (now defined as AI_MATKEY_GLOSSINESS_FACTOR)

Define this one as being AI_MATKEY_GLOSSINESS_FACTOR and add conversion template specialization to convert into bool

@MehdiChinoune Can you please test this against your build to check whether I have now found them all?

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
qt6-quick3d builds now successfully. (To be updated)

**Comment by RichardTea** [comment]
@kimkulling Can you please merge this one so the downstream Qt projects can update?

**Review by kimkulling — APPROVED** [review]

**Comment by jiapei100** [comment]
Works for me, Qt 6.2.2 
However, it's still **NOT** in the release yet....

**Comment by MehdiChinoune** [comment]
QtQuick3D 6.3 won't need this patch https://invent.kde.org/qt/qt/qtquick3d/-/commit/9715cfb94d761aacdc24a0532aeb1d6df7529e67

**Comment by kimkulling** [comment]
Done!

**Comment by wdconinc** [comment]
Just checking if there is additional work needed here? I am looking forward to being able to use a recent version of assimp that includes this patch (due to qt5).

**Comment by RichardTea** [comment]
@wdconinc I had intended to abandon this patch as it had been left on the shelf for so long that it no longer cleanly merged, and another user said Qt had already fixed the dependency - Qt3D should never have used that flag in the first place as it was always rather meaningless.

I'll try to make some time tomorrow to resolve the merge conflict.

**Comment by wdconinc** [comment]
I will leave it up to you to decide. At this point I am stuck on qt 5.15.2 and unable to take advantage (at least easily) of the bugfixes  that qt makes avialable to commercial clients for the 5.15 release. But, I do understand that that is not assimp's problem to solve :-)

**Comment by kimkulling** [comment]
Finally ...

**Pull request merged**
