### PR TITLE
Fix: memory leak in gltf2 importer (fixes #2661)

### LINKED ISSUE #2661: Memory leak in gltf2 importer
There seems to be a memory leak when importing some gltf2 objects:

```
=================================================================
==2509==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7136 byte(s) in 1 object(s) allocated from:
    #0 0x3520a2 in operator new[](unsigned long) (/nt/_out/dbg/bin/ModelExtractor_binary+0x3520a2)
    #1 0x7f1a0432d0e5 in Assimp::glTF2Importer::ImportMeshes(glTF2::Asset&) /tmp/assimp/code/glTF2/glTF2Importer.cpp:447:35
    #2 0x7f1a04332aee in Assimp::glTF2Importer::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) /tmp/assimp/code/glTF2/glTF2Importer.cpp:1239:5
    #3 0x7f1a03c591f2 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) /tmp/assimp/code/Common/BaseImporter.cpp:117:9
    #4 0x7f1a03c74769 in Assimp::Importer::ReadFile(char const*, unsigned int) /tmp/assimp/code/Common/Importer.cpp:646:30
    #5 0x37cceb in ModelExtractor::State::importFromFiles(std::vector<char const*, std::allocator<char const*> > const&) /nt/ModelExtractor/main/main.cpp:104:36
    #6 0x362b92 in main /nt/ModelExtractor/bin/main.cpp:50:26
    #7 0x7f1a0313fb6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)

SUMMARY: AddressSanitizer: 7136 byte(s) leaked in 1 allocation(s).
```

Here is the relevant C++ code for the importer:

```cpp
Assimp::Importer importer;
importer.SetPropertyInteger(AI_CONFIG_PP_RVC_FLAGS, aiComponent_LIGHTS | aiComponent_CAMERAS);
const aiScene *scene = importer.ReadFile(filePath, aiProcess_RemoveComponent | aiProcess_GenSmoothNormals | aiProcess_ImproveCacheLocality | aiProcess_LimitBoneWeights | aiProcess_RemoveRedundantMaterials | aiProcess_GenUVCoords | aiProcess_FindDegenerates | aiProcess_FindInvalidData | aiProcess_Triangulate | aiProcess_OptimizeMeshes | aiProcess_JoinIdenticalVertices);
```

Other details:

- OS: Xubuntu 19.04
- Compiler: Clang 8.0.0
- Branch: Master (built from source on approx. 15 Sep - can't remember exactly)
- The GLB file was exported from Blender 2.80.

I've attached the GLB file that generates the leak.

[3.glb.tar.gz](https://github.com/assimp/assimp/files/3629710/3.glb.tar.gz)

### PR DESCRIPTION
**Pull request by theakman2**
Should fix #2661.

### CODE REVIEW

**Comment by theakman2** [comment]
Hmm, I'm not sure why the AppVeyor build is failing here. This PR only touches a single line code and the AppVeyor errors don't seem to be related. Is the AppVeyor build flaky?

**Comment by kimkulling** [comment]
I guess you need to get the latest version from master. I changed the type of aiString to have the same serialization code for its len.

**Comment by theakman2** [comment]
Great, thank you. That did the trick. All my pull requests are passing now.

**Comment by kimkulling** [comment]
Merged, thank you for the fix!

**Pull request merged**
