### PR TITLE
Make internal errors accessible

### PR DESCRIPTION
**Pull request by MalcolmTyrrell**
There are two main parts to this PR:
1. DeadlyImportError and DeadlyExportError now have formatting built in.
    - I removed all instances of the formatter from callsites
    - I removed many uses of std::string::operator+ and several unnecessary std::string constructions.
    - I've simplified one or two code paths so the way they call DeadlyImportError is more straightforward (e.g. FBX tokenization errors).
2. The Importer API now has an additional method that provides access to the exception which was thrown via a std::exception_ptr. 
    - The existing GetErrorString API remains. 
    - GetException can be used to get full details of exceptions.

Note:  The two aspects of this PR are probably separable and, if requested, I'm willing to go to the trouble of separating them. I'd rather not though :D

A note on motivation: Both of these changes are extremely useful when you want to customize error handling. Part 1 centralizes the formatting, and allows a customized DeadlyImportError some control over the message they carry. Part 2 allows any additional details carried by a customized DeadlyImportError (e.g. a callstack) to be retrieved by the calling context. It additionally allows the calling context to try to make sense of the exceptions which would normally be discarded.

### CODE REVIEW

**Comment by ms-maxvollmer** [comment]
@kkulling Hey Kim! Hope you are doing well :) I know times are busy, and understand when things take a while. This is a high quality change to Assimp that Malcolm has put together, and I really think it would bring a lot of value to get it in soon. Do you think you or someone else with merge rights could review this in the next couple of days? Thank you so much!

**Comment by kimkulling** [comment]
Hi,
sorry for the delay, review is on its way!

Kim

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution. Looks great! Much simpler and easy to get the exception!

**Comment by ms-maxvollmer** [comment]
Thank you so much!

**Pull request merged**
