### PR TITLE
Clean up some warnings

### PR DESCRIPTION
**Pull request by turol**
Cleans up some compiler warnings. No new regression failures on Linux with GCC. Review and run testsuite on a working config before merging. Also the recent changes to the test suite seem to have made mode cases fail (101 currently vs 96 previous).

### CODE REVIEW

**Comment by turol** [comment]
@acgessler ACK or NAK on this please.

**Comment by acgessler** [comment]
Sorry for the delay. One comment only, otherwise looks great.

**Comment by turol** [comment]
Fixed assertion.

**Comment by turol** [comment]
This branch fails to build but I can't see why. I have not touched the failing file, in fact it looks like no-one has touched that file in a year. In addition the error message doesn't appear to match the code. WTF?

**Comment by acgessler** [comment]
#472 should fix it, then we can proceed.

**Comment by acgessler** [comment]
Looks all good now. Thanks for the patience!

**Pull request merged**
