### PR TITLE
[Fedback needed]Minor updates to ASSIMP Viewer

### PR DESCRIPTION
**Pull request by hgdagon**
Pretty much the same as #4510 except I was more careful, since this is a GUI application that very much relies on the script for its UI. Also replaced some SourceForge references to GitHub.

### CODE REVIEW

**Comment by kimkulling** [comment]
Looks fine for me. Just give me a ping when I shall merge it.

**Comment by hgdagon** [comment]
@kimkulling Done!

**Review by kimkulling — APPROVED** [review]
I will merge it.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
