### PR TITLE
Update ObjFileMtlImporter.cpp

### PR DESCRIPTION
**Pull request by elect86**
Fixed grammar

### CODE REVIEW

**Comment by kimkulling** [comment]
You need to change all isages as well, build is broken.

**Comment by elect86** [comment]
You are welcome :)

What are the isages?

**Comment by kimkulling** [comment]
Usage 😁

**Comment by kimkulling** [comment]
Hi, do you have time to fix the misusages?

**Comment by elect86** [comment]
I forgot, I'll do :p

**Comment by kimkulling** [comment]
Thanks a lot, merged!

**Pull request merged**
