### PR TITLE
Additional checks on invalid input

### PR DESCRIPTION
**Pull request by bztsrc**
Extra checks on invalid inputs to make turol happy. Still there's no guarantee that ALL invalid inputs are handled, and never will be, because that's simply irrational to be expected. To account for all possibilities, you'd need to mathematically prove the correctness, which is something that's definitely out of the scope of  a free and open source project. Even paid and big projects can't afford that.

### CODE REVIEW

**Comment by bztsrc** [comment]
Dear @kimkulling,

Your modifications (dubbed "fix scope of variables") broke the code. It does not compile any more. Could you please revert them?
```
/home/travis/build/assimp/assimp/code/M3D/M3DImporter.cpp:766:10: error: ‘j’ was not declared in this scope
```
and
```
/home/travis/build/assimp/assimp/code/M3D/M3DImporter.cpp:774:10: error: ‘i’ was not declared in this scope
```

My last commit (cb623f8) was working perfectly, and it passed all CI tests.

Please revert to those, and I kindly ask you to check if your code at least compiles before you push a commit. Pushing broken code is very problematic to all of us.

Thanks,
bzt

**Comment by turol** [comment]
I don't expect _all_ invalid inputs to be handled but I'd like it to withstand fuzzing for longer than a few seconds. 

Also since it's your repository you can just force-push it yourself, either with the old commit or preferably an up-to-date rebased one. And if you don't want maintainers updateing your PR you can uncheck that checkbox when creating the PR but then you have to synchronize it yourself against master.

**Comment by bztsrc** [comment]
@turol: have you tried cb623f8? It works perfectly on all your invalid inputs. I bet you haven't.

I did synced with master, and I did commit a version which passed all tests. It is not that I don't want maintainers updating my repo, as I could make mistakes that others may fix; but comiting a broken code which doesn't even compile is just wrong (no matter if it was just by a foolish mistake or a deliberate sabotage). I expect the one who broke the code to fix what they broke, it's only fair.

Cheers,
bzt

**Comment by turol** [comment]
No, I have not tried your latest code yet. I'd have carefully pick that commit from your branch. I'll try it once it has been merged to master.

**Comment by kimkulling** [comment]
Sorry for breaking the code.

**Comment by kimkulling** [comment]
One leak less. Thanks for your contribution.

**Pull request merged**
