### PR TITLE
Fix Heap-buffer-overflow READ in Assimp::ObjFileParser::getFace

### LINKED ISSUE #4923: Bug: Issue 54423 in oss-fuzz: assimp:assimp_fuzzer: Heap-buffer-overflow in Assimp::ObjFileParser::getFace
Status: New
Owner: ----
CC: kim.k...@[googlemail.com](http://googlemail.com/) 
Labels: Restrict-View-Commit ClusterFuzz Stability-Memory-AddressSanitizer Reproducible Engine-libfuzzer OS-Linux Security_Severity-Medium Proj-assimp Reported-2022-12-18
Type: Bug-Security

New issue 54423 by ClusterFuzz-External: assimp:assimp_fuzzer: Heap-buffer-overflow in Assimp::ObjFileParser::getFace
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54423

Detailed Report: https://oss-fuzz.com/testcase?key=5781186265350144

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_asan_assimp
Platform Id: linux

Crash Type: Heap-buffer-overflow READ 3
Crash Address: 0x6020000001c0
Crash State:
  Assimp::ObjFileParser::getFace
  Assimp::ObjFileParser::parseFile
  Assimp::ObjFileParser::ObjFileParser
  
Sanitizer: address (ASAN)

Recommended Security Severity: Medium

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_asan_assimp&range=202207310606:202208010603

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5781186265350144

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

### PR DESCRIPTION
**Pull request by sashashura**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54423
Closes #4923

The root cause is that `::atoi(token)` reads beyond `m_DataItEnd` if the string is not null terminated.

### CODE REVIEW

**Comment by turol** [comment]
While this works, allocating a string for every number token is not very fast. It would be better to use `std::from_chars` which can take an end iterator but that requires C++ 17.

**Comment by turol** [comment]
Very nice. Now add some comments to explain why it does that for the next person who has to look at it.

**Review by kimkulling — APPROVED** [review]
Looks fine.

**Comment by kimkulling** [comment]
Merged, thanks for your contribution.

**Pull request merged**
