### PR TITLE
add missing light data to assbin import/export

### PR DESCRIPTION
**Pull request by Gargaj**

### CODE REVIEW

**Review by kimkulling — COMMENTED** [review]
Looks fine, thanks!

**Review by kimkulling — APPROVED** [review]

**Comment by Gargaj** [comment]
Do i need anything for the merge, then? @kimkulling

**Comment by kimkulling** [comment]
I just need some time to do it. It is on its way!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
