### PR TITLE
Fix inits and a couple of empty checks

### PR DESCRIPTION
**Pull request by asmaloney**
- add missing initialization of several class/struct members
- prefer check for empty() over check for size() in OptimizeGraph (empty() is guaranteed to be constant time, size() is not)

### CODE REVIEW

**Comment by acgessler** [comment]
Yes, please. Also for initialization to the default value - false, NULL/nullptr and 0 the value is optional, empty parens will have the same effect, i.e. `: field()`.

**Comment by asmaloney** [comment]
If this is the style you want to "encourage", maybe add it to *CodeConventions.txt*?

I was attempting to be consistent with the code around the areas I was changing.

**Comment by kimkulling** [comment]
Good idea to introduce a conding convention documentation.

**Comment by kimkulling** [comment]
And thanks for the work, merged!

**Pull request merged**
