### PR TITLE
Add build options to fix issues with clang 15.

### PR DESCRIPTION
**Pull request by Jackie9527**
Fix compile issues when building with clang 15.

Compilers and build scripts, as follows:
1. MSVC cl
```
19.34.31937
```

```
@echo off
setlocal
set SRC=D:\CODE\assimp

set BUILD=%SRC%\build-msvc-cl
cmake -B %BUILD% ^
    -S %SRC% ^
    -G "Visual Studio 17" ^
    -DASSIMP_BUILD_ZLIB=ON ^
    -DASSIMP_BUILD_SAMPLES=ON ^
    -DASSIMP_BUILD_DRACO=OFF ^
    -DBUILD_SHARED_LIBS=OFF ^
    -DASSIMP_DOUBLE_PRECISION=OFF ^
    -DASSIMP_BUILD_ASSIMP_TOOLS=ON ^
    -DASSIMP_ASAN=OFF ^
    -DASSIMP_UBSAN=OFF ^
    -DASSIMP_BUILD_TESTS=ON
```
2. MSVC clang-cl
```
clang --version
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
```

```
@echo off
setlocal
set SRC=D:\CODE\assimp

set BUILD=%SRC%\build-msvc-clang-cl
cmake -B %BUILD% ^
    -S %SRC% ^
    -T ClangCl ^
    -DASSIMP_BUILD_ZLIB=ON ^
    -DASSIMP_BUILD_SAMPLES=ON ^
    -DASSIMP_BUILD_DRACO=OFF ^
    -DBUILD_SHARED_LIBS=OFF ^
    -DASSIMP_DOUBLE_PRECISION=OFF ^
    -DASSIMP_BUILD_ASSIMP_TOOLS=ON ^
    -DASSIMP_ASAN=OFF ^
    -DASSIMP_UBSAN=OFF ^
    -DASSIMP_BUILD_TESTS=ON
```
3. msys2 clang
```
$ /clang64/bin/clang --version
clang version 15.0.7
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Tools/msys2/clang64/bin
```

```
#!/bin/sh
export SRC=/d/CODE/assimp
export CLANG_ROOT=/clang64
export PATH=$CLANG_ROOT/bin:$PATH

export BUILD=$SRC/build_msys2_clang
rm -f $BUILD/CMakeCache.txt
cmake -B $BUILD \
    -S $SRC \
    -G "Ninja Multi-Config" \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_C_COMPILER=clang \
    -DASSIMP_BUILD_ZLIB=ON \
    -DASSIMP_BUILD_SAMPLES=ON \
    -DASSIMP_BUILD_DRACO=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DASSIMP_DOUBLE_PRECISION=OFF \
    -DASSIMP_BUILD_ASSIMP_TOOLS=ON \
    -DASSIMP_ASAN=OFF \
    -DASSIMP_UBSAN=OFF \
    -DASSIMP_BUILD_TESTS=ON

cmake --build $BUILD --target unit --config release --parallel
```
4. msys2 gcc
```
$ gcc --version
gcc.exe (Rev10, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
#!/bin/sh
export SRC=/d/CODE/assimp
export CLANG_ROOT=/clang64
export PATH=$CLANG_ROOT/bin:$PATH

export BUILD=$SRC/build_msys2_gcc
rm -f $BUILD/CMakeCache.txt
cmake -B $BUILD \
    -S $SRC \
    -G "Ninja Multi-Config" \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_C_COMPILER=gcc \
    -DASSIMP_BUILD_ZLIB=ON \
    -DASSIMP_BUILD_SAMPLES=ON \
    -DASSIMP_BUILD_DRACO=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DASSIMP_DOUBLE_PRECISION=OFF \
    -DASSIMP_BUILD_ASSIMP_TOOLS=ON \
    -DASSIMP_ASAN=OFF \
    -DASSIMP_UBSAN=OFF \
    -DASSIMP_BUILD_TESTS=ON

cmake --build $BUILD --target unit --config release --parallel
```

See [Diagnostic flags in Clang](https://clang.llvm.org/docs/DiagnosticsReference.html) for more information.

### CODE REVIEW

**Comment by kimkulling** [comment]
Would be great to fix these issues ierative.

**Comment by Jackie9527** [comment]
> Would be great to fix these issues ierative.

I will work on these issues in new PRs.

**Comment by kimkulling** [comment]
Sounds good!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
