### PR TITLE
Improve ValidateDataStructure error reporting

### PR DESCRIPTION
**Pull request by Cgettys**
I was debugging some code and noticed that the ValidationDSProcess code could give me more info than it was with a few minor tweaks (e.g. telling me what the name of the aiNode missing a parent is, etc). I thought these improvements might be handy to others.

I did notice that there doesn't appear to be a unit test for the validation code and was considering starting one. I was wondering if that'd be useful. I'm thinking something along the lines of constructing objects with exactly 1 check that should fail, and then running those objects through the validator to make sure they do. It'd be a fair bit of work, and I'm not sure I'd do all of it at once, but given that it looks like to me that basically every unit test depends on that file to make sure there are no errors, it might be effort well spent. I'm happy to start one that at a minimum covers the cases I modified if that'd be helpful.

### CODE REVIEW

**Comment by Cgettys** [comment]
@kimkulling could I get some feedback on this, especially with regards to whether there should be a unit test for the validator? Thanks for all the effort you guys have put into the library, it's fantastic.

**Comment by kimkulling** [comment]
This pull request **introduces 6 alerts** when merging 80dffb63e86733b43530b7a52bb49a1ae6987d2f into 5c900d689a5db5637b98f665fc1e9e9c9ed416b9 - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-fce5aca4aceba46e1cfb790545eb5b77396e0a0b)

**new alerts:**

* 6 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
This pull request **introduces 2 alerts** when merging 7bb130377395a5f270618538d36690defba30d2f into 5c900d689a5db5637b98f665fc1e9e9c9ed416b9 - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-893fc19fa49656a41cb45005f634c96c2f4759c3)

**new alerts:**

* 2 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 27dc922d096cbe0a1d25c79b541704660db8accb into 5c900d689a5db5637b98f665fc1e9e9c9ed416b9 - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-8d1cf7aa1e0491d8b3478d911cd6605ff403a7e3)

**new alerts:**

* 2 for Wrong type of arguments to formatting function

**fixed alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging 5fd9789fc3006d819266f0f61b791c984731d1a8 into 5c900d689a5db5637b98f665fc1e9e9c9ed416b9 - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-17e428ae7ccb70b682b2402a13135d60bfbc24f3)

**fixed alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cgettys** [comment]
Again, I'm happy to start adding unit tests for ValidateDSProcess, as mentioned in the original PR above, but given that I haven't gotten a response and it has no warnings, I'm marking this ready for review.

**Comment by kkulling** [comment]
Hi,

sorry for my late response. I was busy in my daytime-job. I already start to do a review, but I haven't finished this until now.

Thanks a lot for your help! 

Kim

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging 90dbd8f35027c23fbd3f6abc03c711ba067df6c3 into 152cddedd32853a571045a26dca6e910ec90813e - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-db140be30ea61eede3612a74df2ebed1d16e67b2)

**fixed alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Pull request merged**
