### PR TITLE
PBR material support

### PR DESCRIPTION
**Pull request by spotaws**
First off, on behalf of the [Lumberyard](https://aws.amazon.com/lumberyard/) team at Amazon, thank you for assimp. It has been very helpful to us.

This change does a few things to the FBX code:

- handles the "Maya|emissive" property
- Adds support for PBR materials
- Adds "float" to a conditional check in ReadTypedProperty (FBXProperties.cpp), previously only "Float" was checked here

Please consider this change for merge, thanks!

### CODE REVIEW

**Comment by krishty** [comment]
@kimkulling I’m a little confused over the best practice here: glTF2 defines PBRT materials as well (similar, but slightly different, so I don’t think they can be re-used). But it defines them in a separate file `pbrmaterial.h`. What’s preferred – defining these properties in `material.h`, or in a dedicated header?

**Comment by RichardTea** [comment]
I think the PBR items should be defined in materials.h
At the moment glTFv2 is the only assimp format that supports PBR, and that's clearly going to change as all "modern" formats are getting extensions for it.
There are a couple of different PBR models though, so they aren't all going to be fully interchangeable.

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Hi,
for me moving the defines into the material-header seems to be the right way. At this moment the separate header for pbr-based material attributes feels unnatural. I guess I will refactor this.

And sorry for the late response. I was a little bit busy with changing my job :-).

Kim

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by RichardTea** [comment]
@spotaws Can you please add some documentation for these properties?

I do not understand what each of these new PBR properties actually mean:
`$mat.useMetallicMap` is a Float, so where is the actual Metallic map image?

**Comment by spotaws** [comment]
> @spotaws Can you please add some documentation for these properties?
> 
> I do not understand what each of these new PBR properties actually mean.
> For example, `$mat.useMetallicMap` is a Float. Where is the actual Metallic map image it refers to?

As part of the work of [implementing the Atom renderer in Lumberyard](https://aws.amazon.com/blogs/gametech/splitting-the-atom-introducing-lumberyards-new-photorealistic-renderer/), the team needed to support PBR material properties. Specifically, the initial work was done to support PBR materials created in Autodesk Maya. When the FBX files generated by Maya were analyzed, the data inside it was very Maya specific.

Lumberyard did not attempt to implement all of the possible Maya PBR material properties in assimp, just the ones that the Atom renderer uses, which map up mainly to the "Stingray Physically Based Shader", documented by Autodesk [here](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/Maya-LightingShading/files/GUID-13B0F0A6-39D5-4668-A722-DD743877D2E3-htm.html) and [here](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/Maya-LightingShading/files/GUID-04F2FFA5-1797-4FEF-8A52-AEE00C47224E-htm.html). 

To your question on the metallic map image, quoting from the Autodesk docs, "Your metallic map is a mask that determines the areas of your object that are metallic and the areas that are not. This value should be 0 or 1, with non-metals as 0 and metals as 1. The map value should represent the top layer of the material; therefore, painted metal should not be set to 1 as paint is a non-metal." 

The relevant bit of a Maya generated ASCII FBX file with PBR properties looks like this (I can share the full FBX file if that is helpful):

<pre>
        Material: 1763546001216, "Material::StingrayPBS1", "" {
                Version: 102
                ShadingModel: "unknown"
                MultiLayer: 0
                Properties70:  {
                        P: "Maya", "Compound", "", ""
                        P: "Maya|TypeId", "int", "Integer", "",1166017
                        P: "Maya|TEX_global_diffuse_cube", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|TEX_global_specular_cube", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|TEX_brdf_lut", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|use_normal_map", "float", "", "",0
                        P: "Maya|uv_offset", "Vector2D", "Vector2", "",0,0
                        P: "Maya|uv_scale", "Vector2D", "Vector2", "",1,1
                        P: "Maya|TEX_normal_map", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|use_color_map", "float", "", "",0
                        P: "Maya|TEX_color_map", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|base_color", "Vector3D", "Vector", "",0.504299998283386,0.308099985122681,0.0790999978780746
                        P: "Maya|use_metallic_map", "float", "", "",0
                        P: "Maya|TEX_metallic_map", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|metallic", "float", "", "",1
                        P: "Maya|use_roughness_map", "float", "", "",0
                        P: "Maya|TEX_roughness_map", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|roughness", "float", "", "",0.333
                        P: "Maya|use_emissive_map", "float", "", "",0
                        P: "Maya|TEX_emissive_map", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|emissive", "Vector3D", "Vector", "",0,0,0
                        P: "Maya|emissive_intensity", "float", "", "",0
                        P: "Maya|use_ao_map", "float", "", "",0
                        P: "Maya|TEX_ao_map", "Vector3D", "Vector", "",0,0,0
                }
        }
</pre>

**Comment by RichardTea** [comment]
Sorry, I wasn't clear enough.

This patch adds support for importing Maya's PBR material extension.

However, it adds a multitude of new Material properties to Assimp.

What is the meaning of each of these new properties?

These ones are relatively clear, however they do need some definitions as to the applicable ranges:
`AI_MATKEY_BASE_COLOR, AI_MATKEY_METALLIC_FACTOR, AI_MATKEY_ROUGHNESS_FACTOR, AI_MATKEY_EMISSIVE_INTENSITY`

However, it is not clear what the others mean.
I suspect they are actually internal to the FBX format and shouldn't exist as formal assimp material properties:
`AI_MATKEY_USE_COLOR_MAP, AI_MATKEY_USE_METALLIC_MAP, AI_MATKEY_USE_ROUGHNESS_MAP, AI_MATKEY_USE_EMISSIVE_MAP, AI_MATKEY_USE_AO_MAP`

Are these really floats, or are they actually internal FBX flags defining the meaning of some of the texture maps?
- If they are floats, what should my renderer do with each of the value?
- If they are actually flags, then the property should be removed from material.h and instead the FBX Importer should use the value in the FBX file to determine how to convert the FBX file into Assimp's generalised internal format.

For example, when importing an FBX file containing 3dsMax PBR materials, it checks the value of 3dsMax|main|useGlossiness
- The the flag is not set, no texture is imported
- If == 1, then the texture is imported as aiTextureType_SHININESS
- If == 2 then the texture is imported as aiTextureType_DIFFUSE_ROUGHNESS
- If it is set to something else, then the texture is not imported and a warning given

**Comment by spotaws** [comment]
I understand now. The "use_" flags do seem to be internal flags as you describe. The team will work on a follow-up change to appropriately handle this.

**Pull request merged**
