### PR TITLE
- Apply mechanism to decide use for IrrXML external or internal

### PR DESCRIPTION
**Pull request by heliocastro**
Several distributions usually decide for shared external libraries
instead of an usual embedded, for security reasons, duplicatiion issues.
This change enable the possibility to set SYSTEM_IRRXML=ON for detect
and build against a system installed irrxml.
By default, the internal copy is compiled.

Changes on build:
- Added a FindIrrXML cmake module.
- Moved the source recipe for proper CMakeLists inside contrib directory
- Includes aren't path based anymore, using the provided INCLUDE_DIR
- Compiler options are grouped in a single entry on main CMakeLists

Note: Current internal assimp irrXML is older than upstream irrlicht 1.8.4.
To enable usage of this version, code need to be patched.

### CODE REVIEW

**Comment by kimkulling** [comment]
Thanks, looks much cleaner now. I will merge it!

**Comment by rdb** [comment]
This change broke linking with Assimp on Windows:
```
assimp.lib(X3DImporter.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(ColladaParser.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(OgreXmlSerializer.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(D3MFOpcPackage.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(AMFImporter.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(OgreImporter.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(XGLLoader.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
assimp.lib(D3MFImporter.obj) : error LNK2001: unresolved external symbol "class irr::io::IIrrXMLReader<char,class irr::io::IXMLBase> * __cdecl irr::io::createIrrXMLReader(class irr::io::IFileReadCallBack *)" (?createIrrXMLReader@io@irr@@YAPEAV?$IIrrXMLReader@DVIXMLBase@io@irr@@@12@PEAVIFileReadCallBack@12@@Z)
```
Could it be reverted until the PR is fixed?

**Comment by heliocastro** [comment]
Hi

Can you please post which Microsoft compiler are you using ?
I surprised that the automate CI tests on GitHub cover the basis, but  i
will be happy to look on this issue.
Sorry for the inconvenience.

**Comment by rdb** [comment]
I'm using Microsoft Visual Studio 2015, and made a static build of Assimp.  I used RelWithDebInfo x64 configuration.

**Comment by Sailsman63** [comment]
Also broken on Linux x64. The cause is in CMakeLists.txt, in the line 170s area. `CMAKE_C_FLAGS` _must_ include `-fPIC` when linking shared libs on 64 bit, due to the overall large size of the project. Also, the reason that this was originally gated on `CMAKE_SIZEOF_VOID` is that it was thought that certain deploy environments, such as ARM 32 bit, are often space constrained enough that the smaller binary possible when skipping `fPIC` would be worth effort.

**Comment by heliocastro** [comment]
Ok, I will change the code for corner cases, including arm 32 bits, but
Android build of CI and clang worked ok. For Linux general I have sure is
not broken as is one of the main platforms on Fedora, and to tests I even
do a formal build against several distros releases and architectures, more
than the regular assimp CI on github and I do have Ubuntu as well at home
to test. I just don't have Windows in all forms and need to check latest
report.
We have it working with shared and static to both cases, just the ppc64 and
s390x have a big endian issue to be solved.

**Comment by heliocastro** [comment]
@rdb Hi again. How are you building assimp ? Is it using CMake or you have an internal msvc project ?
I set up an personal windows CI with upstream changes using msvc 2015 64 bits
I'm using options -DBUILD_SHARED_LIBS=OFF but maybe i'm missing something becuase build went fine, so we do have an stsic build of assimp.
You can see it here https://ci.appveyor.com/project/heliocastro/assimp

**Comment by Sailsman63** [comment]
If you note the comment in the section that you removed, (see diff in https://github.com/assimp/assimp/commit/4a0171bd82adb9bca4d50c1190bf670d75052d06 ) you will note that the `-fPIC` option is necessary for `-DBUILD_SHARED_LIBS=ON` which is needed for my use case.

**Comment by heliocastro** [comment]
@Sailsman63 You're absolutely right. The fact that automated tests not pick this by default is bad.
I did this mistake due revert the first patch option where i introduced CMAKE_POSITION_INDEPENDENT_CODE instead of -fPIC directly, but due assimp officially support older cmake version than 3.0.2, when this option was included, invalidated the case.
I will fix in subsequent pull request.

**Pull request merged**
