### PR TITLE
[gltf2] node name conflict fix

### LINKED ISSUE #1600: Regression on GLTF2 import
Hi,

I think this commit (0b04ae1d91a561aa2bf6c40edf8f490b45b7b7fd) broke some validation tests on gltf import. 

To reproduce: 
- download the khronos gltf models corpus.
https://github.com/KhronosGroup/glTF-Sample-Models/
- execute assimp_cmd on each file : 
`for file in **/**/*.glb; do "assimp.exe" info "$file"; done`

Lot of files fails with error
> ERROR: Failed to load file: Validation failed: aiScene::mCameras[0] has the same name as aiScene::mNumCameras[1]

or
> ERROR: Failed to load file: Validation failed: aiScene::mCameras[0]: there are more than one nodes with  as name

For example, `ReciprocatingSaw/glTF-Binary/ReciprocatingSaw.glb` will show a validation error.

Thanks a lot for your lib,

Alex

### PR DESCRIPTION
**Pull request by dhritzkiv**
This is an improvement on #1595, and also introduces tests for GLB files.
Fixes #1600 

@aavenel, could you test these changes?

@kimkulling is including the 2CylinderEngine.glb model okay?  It's just over a MB, but it's the smallest GLB I could find that triggered the error in the above issue.

### CODE REVIEW

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Comment by aavenel** [comment]
Thanks a lot for your patch. It works great ! I've still an error with some files but I think this is another issue.

> ERROR: Failed to load file: OBJ: Invalid face indice
> assimp info: Unable to load input file NormalTangentTest/glTF-Binary/NormalTangentTest.glb

> ERROR: Failed to load file: OBJ: Invalid face indice
> assimp info: Unable to load input file MetalRoughSpheres/glTF-Binary/MetalRoughSpheres.glb

**Comment by dhritzkiv** [comment]
Can confirm: the errors with MetalRoughSpheres.gltf are unrelated to the code changes in #1595.

Might have to do with my #1557 PR

**Comment by dhritzkiv** [comment]
Interesting that the GLB files are interpreted as OBJs… Hmm.

**Pull request merged**
