### PR TITLE
Assimp

### PR DESCRIPTION
**Pull request by thakur-virendra**
Fix unit test by updating project version and major minor version number

### CODE REVIEW

**Review by thakur-virendra — COMMENTED** [review]
need to create a pull request for v5.0.1

**Comment by andrewmcdonald-oxb** [comment]
Hello, is this the cause of the failure in unit test `utVersion.aiGetVersionRevisionTest`? I discovered this when building the 5.2.0 zip package on Mac OS 11.6 Big Sur.

**Comment by thakur-virendra** [comment]
@andrewmcdonald-oxb  Yes , it fails in aiGetVersionRevisionTest unit test . This fix resolve unit test failure. I am using assimp v5.0.1

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
