### PR TITLE
Fix some bugs found with afl

### PR DESCRIPTION
**Pull request by turol**
Fixes assorted bugs found with afl http://lcamtuf.coredump.cx/afl/

Do not merge without review. Not regression tested since it doesn't run very well on Linux. Also there's some doubt about what we should do on corrupted input. Try to continue or just give up immediately?

Also there are many more, this is just the first batch.

### CODE REVIEW

**Comment by acgessler** [comment]
Cool. I'll have a look tonight.

**Comment by turol** [comment]
Also should I rewrite and rebase the whole series or add more commits to fix the issues you pointed out?

**Comment by acgessler** [comment]
A rebase would be cleaner but if it is less effort for you, feel free to just add more commits.

**Comment by turol** [comment]
V2, fix issues raised in review.

**Comment by turol** [comment]
Both rebase and more commits are equally easy but it seems github loses the comments when the commits change (obviously). Hope no-one misses them :)

**Comment by acgessler** [comment]
Thanks!

Running the regression test suite, we added 5 failures:

../models-nonbsd/MD2/horse.md2
../models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--GP-Gun.lwo
../models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Chasis.lwo
../models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Arm-Tip.lwo
../models-nonbsd/LWO/LWO2/LWSReferences/QuickDraw--Arm-Shoulder.lwo

I'll look into the lwo files later. md2 is a mystery :-)

**Comment by turol** [comment]
Those LWO files are among the tests which fail on Linux. Maybe the reason they fail is the models are not quite correct and cause undefined behavior in the library?

Also no idea on md2. There's nothing in this set which should be able to cause that.

**Comment by acgessler** [comment]
Apologies - I misread the output. We really need to fix the regression suite reporting.

here is the diff:

     ../models/X/test_cube_compressed.x -cfull;../results/tmp/test_cube_compressed.x_0x28c95c8a/EXPECT 
 	../models/X/test_cube_compressed.x -og -om -vds;../results/tmp/test_cube_compressed.x_0x6ce1810d/EXPECT 
 	../models/X/test_cube_compressed.x -ptv -gsn -cts -db;../results/tmp/test_cube_compressed.x_0xc2466795/EXPECT 
 	../models/X/test_cube_compressed.x -vds -jiv;../results/tmp/test_cube_compressed.x_0x1e8baf0d/EXPECT 
 	../models/X/test_cube_compressed.x ;../results/tmp/test_cube_compressed.x_0x89b6c185/EXPECT

**Comment by turol** [comment]
So the .X loader fix is wrong. Can you drop that one and merge the rest?

**Comment by acgessler** [comment]
I tried around and a variant of the test that seems to work is `(P + ofs > End + 2)`. Confirmed with test_cube_compressed.x and another compressed X file I have in my collection.

I have no idea why this would be the correct test, it seem we're still in danger of reading one byte off. It could be an implementation detail of zlib that I am not aware of.

Would you mind changing?

**Comment by turol** [comment]
Sure, here it is.

**Comment by acgessler** [comment]
Awesome. Thanks for your patience!

**Comment by turol** [comment]
Don't thank me yet, I'm about to file a bug with several hundred more crashing and hanging testcases. Because there's no way I could go through all of them myself.

**Pull request merged**
