### PR TITLE
Asan

### PR DESCRIPTION
**Pull request by turol**
DON'T MERGE YET! BREAKS THE BUILD!

AddressSanitizer take two. Some more fixes, now it's stuck on this:

```
ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060007323c0 at pc 0x000000d54122 bp 0x7ffd357ab450 sp 0x7ffd357ab448
READ of size 1 at 0x6060007323c0 thread T0
    #0 0xd54121 in Assimp::SkipToken(char const*&) assimp/code/ParsingUtils.h:236:30
    #1 0xd89a14 in Assimp::ObjFileParser::getNumComponentsInDataDefinition() assimp/code/ObjFileParser.cpp:290:9
    #2 0x75cdd4 in TestObjFileParser::testGetNumComponentsInDataDefinition() assimp/test/unit/utObjTools.cpp:67:16
    #3 0x75c2b0 in utObjTools_countComponents_TwoLines_Success_Test::TestBody() assimp/test/unit/utObjTools.cpp:113:23
    #4 0x6a15cb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #5 0x667a60 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #6 0x633759 in testing::Test::Run() assimp/test/../contrib/gtest/src/gtest.cc:2474:5
    #7 0x6353f1 in testing::TestInfo::Run() assimp/test/../contrib/gtest/src/gtest.cc:2656:5
    #8 0x636441 in testing::TestCase::Run() assimp/test/../contrib/gtest/src/gtest.cc:2774:5
    #9 0x64545c in testing::internal::UnitTestImpl::RunAllTests() assimp/test/../contrib/gtest/src/gtest.cc:4649:11
    #10 0x6ad866 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #11 0x66d020 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #12 0x644a76 in testing::UnitTest::Run() assimp/test/../contrib/gtest/src/gtest.cc:4257:10
    #13 0x6b9370 in RUN_ALL_TESTS() assimp/test/../contrib/gtest/include/gtest/gtest.h:2233:10
    #14 0x6b9228 in main assimp/test/unit/Main.cpp:26:18
    #15 0x7f05547472e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #16 0x549299 in _start (assimp/asan/test/unit+0x549299)

0x6060007323c0 is located 0 bytes to the right of 64-byte region [0x606000732380,0x6060007323c0)
allocated by thread T0 here:
    #0 0x6188d0 in operator new(unsigned long) (assimp/asan/test/unit+0x6188d0)
    #1 0x72553b in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/ext/new_allocator.h:111:27
    #2 0x7254db in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/alloc_traits.h:436:16
    #3 0x724e02 in std::_Vector_base<char, std::allocator<char> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_vector.h:172:20
    #4 0x72455d in std::vector<char, std::allocator<char> >::_M_default_append(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/vector.tcc:571:28
    #5 0x723c10 in std::vector<char, std::allocator<char> >::resize(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_vector.h:692:4
    #6 0x75c233 in utObjTools_countComponents_TwoLines_Success_Test::TestBody() assimp/test/unit/utObjTools.cpp:109:5
    #7 0x6a15cb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #8 0x667a60 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #9 0x633759 in testing::Test::Run() assimp/test/../contrib/gtest/src/gtest.cc:2474:5
    #10 0x6353f1 in testing::TestInfo::Run() assimp/test/../contrib/gtest/src/gtest.cc:2656:5
    #11 0x636441 in testing::TestCase::Run() assimp/test/../contrib/gtest/src/gtest.cc:2774:5
    #12 0x64545c in testing::internal::UnitTestImpl::RunAllTests() assimp/test/../contrib/gtest/src/gtest.cc:4649:11
    #13 0x6ad866 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2402:10
    #14 0x66d020 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) assimp/test/../contrib/gtest/src/gtest.cc:2438:14
    #15 0x644a76 in testing::UnitTest::Run() assimp/test/../contrib/gtest/src/gtest.cc:4257:10
    #16 0x6b9370 in RUN_ALL_TESTS() assimp/test/../contrib/gtest/include/gtest/gtest.h:2233:10
    #17 0x6b9228 in main assimp/test/unit/Main.cpp:26:18
    #18 0x7f05547472e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
```

SkipToken reads past the end of buffer because it doesn't check for '\0' terminator. Would it be safe to add that? Or should we somehow pass the size of the buffer down to SkipToken? What's the right fix here?

### CODE REVIEW

**Comment by turol** [comment]
Looks like GCC doesn't treat memory leaks as fatal while Clang does. This can probably be merged now, i'll experiment with clang build in another PR. @jaredmulconry ?

**Comment by jaredmulconry** [comment]
@turol I believe the default behaviour is that a report from asan when compiled with clang is a run failure. I think there's a way of configuring that, but we may just want to go leak free instead. I'm happy to colab with you on this.

**Comment by turol** [comment]
And I think we should merge this to prevent introduction of new issues while we work with Clang in another PR. Do you agree?

**Comment by jaredmulconry** [comment]
Absolutely. This is going to improve the quality of contributions enormously.

**Comment by jaredmulconry** [comment]
@kimkulling Merge me <:)

**Comment by kimkulling** [comment]
Merged, thanks a lot for these fixes. Greate contribution.  Until now I didn't know that you can do these tests with clang.

**Pull request merged**
