### PR TITLE
ConvertToLHProcess now inverts viewing direction

### PR DESCRIPTION
**Pull request by sutajo**
The viewing direction of cameras should be inverted during conversion to a left handed coordinate system.

### CODE REVIEW

**Comment by sutajo** [comment]
Reverted commit https://github.com/assimp/assimp/commit/cdfdd75a66e2323bd834f923798d3043ad3deaf8 because it makes the same mistake as the gltf 2 importer. Cameras must be initialized to their default values and should only be pretransformed if requested with PretransformVertices.

This has been an issue before:
https://github.com/assimp/assimp/issues/2115

**Review by kimkulling — APPROVED** [review]
Looks fine for me.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by beholders-eye** [comment]
While cross building it from Exherbo Linux, I'm getting the error bellow:

```
/var/tmp/paludis/build/media-libs-assimp-scm/work/assimp-scm/code/PostProcessing/ConvertToLHProcess.cpp:244:26: error: no match for 'operator*' (operand types are 'float' and 'aiVector3D' {aka 'aiVector3t<double>'})
  244 |     pCam->mLookAt = 2.0f * pCam->mPosition - pCam->mLookAt;
      |                     ~~~~ ^ ~~~~~~~~~~~~~~~
      |                     |            |
      |                     float        aiVector3D {aka aiVector3t<double>}
I
```

Using gcc 12:

```
gcc --version
gcc (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also tried with gcc 9

Maybe I'm doing something wrong while setting CMake build options?

**Comment by sutajo** [comment]
This should be fixed by #5073

**Comment by beholders-eye** [comment]
Yeah, it did, thanks a lot @sutajo !

**Comment by monsieurgustav** [comment]
A bit late obviously but I'd like to discuss this change.
To me it doesn't make sense: the camera is looking at a location, already expressed in a left or right handed space.
Z being forward or backward must be handled when building the view matrix, not in the look-at vector.

@sutajo @kimkulling Could you explain what it made sense for you?

**Pull request merged**
