### PR TITLE
Fix invalid read of `uint` from `uvwsrc`

### PR DESCRIPTION
**Pull request by JulianKnodt**
Previously was reading a uint, which always failed. Since the output was never checked, this seemed to work, and works fine for most models since they only use UV channel 0.

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]
Looks fine, is there a model to test this?

**Comment by JulianKnodt** [comment]
Let me find one, I think I cannot release the one I've been testing with

**Comment by JulianKnodt** [comment]
image

[sphere_two_uv.zip](https://github.com/assimp/assimp/files/13300350/sphere_two_uv.zip)

I had to zip it because github apparently doesn't support just uploading raw glb files?

**Comment by kimkulling** [comment]
Merged, thanks a lot dor your contribution.

**Pull request merged**
