### PR TITLE
Removed usage of Boost static assert.

### PR DESCRIPTION
**Pull request by sherief**
Fixes issue #824.

### CODE REVIEW

**Comment by sherief** [comment]
@kimkulling / @acgessler  Can I get a review?

**Comment by kimkulling** [comment]
Travis build is broken

**Comment by turol** [comment]
You need to set C++11 mode. This is slightly complicated because older versions of GCC need "std=c++0x" but newer versions prefer "std=c++11". You might also have to check for some minimum version of GCC/clang.

**Comment by sherief** [comment]
Can someone point me in the right direction / help with enabling C++0x / C++11 on all configs?

**Comment by kimkulling** [comment]
Check the global cmake-file, look out for the cpp-flags. I can do this later this week. Unfortunately i am ill at the moment.

**Comment by sherief** [comment]
Sorry to hear that, hope you feel better soon!

**Comment by sherief** [comment]
@kimkulling Any help on this one?

**Comment by mensinda** [comment]
Adding `set_property( GLOBAL PROPERTY CXX_STANDARD 11 )` somewhere in the root CMakeLists.txt (maybe ca. line 23) should do the trick.

This will/should enable c++11 support for all compilers.

Links:

https://cmake.org/cmake/help/v3.5/prop_tgt/CXX_STANDARD.html
https://cmake.org/cmake/help/v3.5/command/set_property.html

**Comment by kimkulling** [comment]
SO last but not least we are supporting c++11.

**Comment by sherief** [comment]
WOOT!

**Pull request merged**
