### PR TITLE
Add ExportProperties

### PR DESCRIPTION
**Pull request by Madrich**
Add class for ExportProperties without changing the external interface
c.f. XFile Export how to use it

### CODE REVIEW

**Comment by acgessler** [comment]
Looks good, a few comments. Also let's wait for the CI build.

Thanks!

**Comment by Madrich** [comment]
Should I do all the stuff?

**Comment by Madrich** [comment]
I did it already, you was right ....

**Comment by acgessler** [comment]
Yes please. I don't mean to be nitpicky, but this is a fairly invasive change affecting the public API so we need to be careful as we have to maintain it for the next 200000 years.

**Comment by Madrich** [comment]
Did it (hopefully right).
Dont care, this is not nitpicky. I do not like to maintain the api for the next 200000+ years too.
Found an other issue in PreTransformVertices, do not use brackets as names. Fixed it.

**Comment by Madrich** [comment]
Had to get back from the last change and add a function to change the name conform in XFileExporter.
Now, I hope you can merge ...

**Comment by acgessler** [comment]
Some more comments. But we're getting there, it's a great patch to get in.

**Comment by Madrich** [comment]
Good work. Thanks for your review. I beleave this is a good patch too.

**Comment by acgessler** [comment]
I'll merge and follow up within the next 1-2 days.

**Pull request merged**
