### PR TITLE
Fix mingw debug build

### LINKED ISSUE #2315: Mingw-5.1.0 Compilation Error ld `-mbig_obj` not supported
I was trying to build via the Code Blocks mingw, which is packaged with mingw-5.1.0 and ran into an error.

Windows 10
Mingw-5.1.0 (Code Blocks)
CMD, not msys

```
set path=code_blocks_mingw_bin;%path%
pushd assimp-4.1.0
mkdir build
pushd build
cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON ..
mingw32-make -j5
popd
popd
```

make fails because option `-mbig_obj` was not supported. Same script works fine for gcc 7.1

### LINKED ISSUE #2361: Compilation fail with mingw
Hello! I'm trying to compile Assimp using mingw32-make, but it fails. How I do it:
```
congard@DESKTOP-QQROP4Q MINGW64 /d/Dev/assimp-master
$ cmake -G "MinGW Makefiles" CMakeLists.txt
-- Shared libraries enabled
-- Looking for DirectX...
-- DirectX_PREFIX_PATH changed.
-- Could not locate DirectX
-- Looking for ZLIB...
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Could not locate ZLIB
-- compiling zlib from sources
CMake Deprecation Warning at contrib/zlib/CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Could NOT find rt (missing: RT_LIBRARY)
INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD STEP
-- Disabled formats:
CMake Warning at tools/assimp_qt_viewer/CMakeLists.txt:26 (MESSAGE):
  Build of assimp_qt_viewer is disabled.  Unsatisfied dendencies: Qt5


-- Configuring done
-- Generating done
-- Build files have been written to: D:/Dev/assimp-master

congard@DESKTOP-QQROP4Q MINGW64 /d/Dev/assimp-master
$ mingw32-make
[  5%] Built target zlib
[ 10%] Built target zlibstatic
[ 10%] Building CXX object contrib/irrXML/CMakeFiles/IrrXML.dir/irrXML.cpp.obj
c:/win-builds/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/as.exe: unrecognized option `-mbig-obj'
contrib\irrXML\CMakeFiles\IrrXML.dir\build.make:62: recipe for target 'contrib/irrXML/CMakeFiles/IrrXML.dir/irrXML.cpp.obj' failed
mingw32-make[2]: *** [contrib/irrXML/CMakeFiles/IrrXML.dir/irrXML.cpp.obj] Error 1
CMakeFiles\Makefile2:233: recipe for target 'contrib/irrXML/CMakeFiles/IrrXML.dir/all' failed
mingw32-make[1]: *** [contrib/irrXML/CMakeFiles/IrrXML.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

congard@DESKTOP-QQROP4Q MINGW64 /d/Dev/assimp-master
```
On Linux, I successfully compiled and installed Assimp, on Windows 10 I can not. What could be the problem?

### LINKED ISSUE #2406: StepFileGen1.cpp compilation error on MinGW-64
When trying to compile on Windows with MinGW-64 I get the following error:

```
[ 70%] Building C object code/CMakeFiles/assimp.dir/__/contrib/zip/src/zip.c.obj
C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\assimp.dir\Importer\StepFile\StepFileGen1.cpp.obj: section .xdata$_ZNSt10_Head_baseILy0EPN6Assimp8StepFile29directed_dimensional_locationELb0EE7_M_headERKS4_: string table overflow at offset 10000029
C:\Users\username\AppData\Local\Temp\ccIXyKsu.s: Assembler messages:
C:\Users\username\AppData\Local\Temp\ccIXyKsu.s: Fatal error: can't close CMakeFiles\assimp.dir\Importer\StepFile\StepFileGen1.cpp.obj: File too big
mingw32-make.exe[3]: *** [code\CMakeFiles\assimp.dir\build.make:2485: code/CMakeFiles/assimp.dir/Importer/StepFile/StepFileGen1.cpp.obj] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:290: code/CMakeFiles/assimp.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:436: test/CMakeFiles/unit.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:241: unit] Error 2
```

This only happens when compiling in debug mode. Release mode works fine.

### PR DESCRIPTION
**Pull request by Cgettys**
* Remove old non-maintained mingw makefile to prevent confusion
* Added notes on building with MinGW to Build.md (Closes #2361)
* Force use of MinGW Compiler version > 7.0 (Closes #2315 ?)
* Fix MinGW Debug Build (WIP - when done closes #2406 )

### CODE REVIEW

**Comment by Cgettys** [comment]
@kimkulling I've been working on the mingw issues too. Not entirely successful, but thought I'd put this up so that we don't duplicate effort/ so that we can share info. I got the file too large error to go away using per-file compiler flags, but am now running into what seems to be a duplicate of #1886 (all the debug symbols are exported and dlls can export a max of ~65k symbols)

**Comment by JekaS178RUS** [comment]
Cool, nice to see that someone trying to deal with mingw build. Currently I am using only release build.

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Comment by tilkinsc** [comment]
MinGW compiler version 7.0 is a bold claim. I think 6.3.0 would be fine to use at the minimum. Have to check the earliest possible that can be used.

**Comment by Cgettys** [comment]
@tilkinsc That's an absolutely fair point. I should definitely clarify what I meant, I'll PR it in a bit. What is actually being checked for and what I said, albeit in a very unclear way is that the version of g++ that mingw supplies is >7. E.g. mingw-w64 v5.0 is fine I believe (and I think that's what I tested it with, though I'll go back and check), since it supplies g++ 7.3.0.  g++ version != mingw version. I checked it that way because cmake can check the compiler version much more easily than the "mingw version".  So basically, iirc, Mingw 4.0 has issues and doesn't have g++ > 7.0.0, mingw-w64 5.0 & 6.0 both supply g++ > 7.0.0. But still, if you can get an older version of g++-mingw-w64++ to work, I'll happily update the version. Iirc did some digging and couldn't find exactly what version it was added in, so I erred on the side of what I knew worked rather than trying to guess what version they introduced it in (the last thing I wanted to do was subject Kim to people saying "it says it should work but it doesn't"). Also, could you check whether the check properly flags the broken version of mingw you experienced the issue on? As mentioned, mingw version is separate equal g++ version, so I want to make sure I got it right.

Also, @kimkulling the last bullet point was listed as wip - 2406 should remain open. Sorry about that, was going to come back and finish that but I've been crazy busy the last few weeks.

**Comment by tilkinsc** [comment]
If I get the nerve to test it I'll happily! :)

**Pull request merged**
