### PR TITLE
Collada exporter: fix unicode.

### PR DESCRIPTION
**Pull request by StepanHrbek**

### CODE REVIEW

**Comment by StepanHrbek** [comment]
This seems to depend on build settings, everything is good with gcc, clang, and with my own vcxproj files, only AppVeyor fails with his vcxproj file. I'm not skilled with cmake so I don't want to debug this....maybe someone knows what's wrong?

Old code calls isalnum(c) from <cctype>, my code calls isalnum(c,loc) from <locale>. And as there already is std::locale, I did not bother including <locale>, it has to be included somewhere. But then AppVeyor doesn't find isalnum(c,loc).

**Comment by StepanHrbek** [comment]
Rather than debugging cmake, I would rewrite isalnum to strchr.

**Comment by StepanHrbek** [comment]
Ok, it works now. 39ab716 fails for reasons I can't reproduce, so 24f0314 reimplements it.

**Comment by kimkulling** [comment]
Thanks a lot, just merged it!

**Pull request merged**
