### PR TITLE
First pass at simplifying PBR

### PR DESCRIPTION
**Pull request by RichardTea**
Removed 'core' set of GLTF-specific properties, use the same generic ones used by FBX 3DS Max PBR importer

Added notes about use of PBR BRDF/BSDF properties
Added some additional values to material enums

Part of #3949

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Cool, thanks a lot for this first step. Merged!

**Comment by lazka** [comment]
This breaks the qt5-quick3d build because it removes various macros. Was that on purpose?

**Comment by RichardTea** [comment]
Sorry about that, I didn't think anyone was using them as they appeared to be a private prototype.
I'll put together a PR that puts them back into the gltf-pbr header and marks it as deprecated.

**Comment by lazka** [comment]
I'm just a user/packager of qt5, so I don't know if qt is doing something wrong here :) I just updated to the new release.

I've downgraded to assimp 5.0 for now.

**Pull request merged**
