### PR TITLE
Fix overlapping merges

### PR DESCRIPTION
**Pull request by asmaloney**
One of the two branches should have been rebased before merging since they both touch the same code...

### CODE REVIEW

**Comment by acgessler** [comment]
Thanks for noticing!

**Comment by acgessler** [comment]
@kimkulling Let's not merge pull requests without waiting for new CI builds.

**Comment by asmaloney** [comment]
If I may make another suggestion - if whoever is doing the merging has merged a PR, then before merging any others they should require they be rebased first so it's up the the requester to fix any issues.

That way you end up with clean merges and avoid the problem we had here which broke the build.

**Comment by kimkulling** [comment]
@acgessler Sounds good!

**Pull request merged**
