### PR TITLE
I ran into an error while processing coloured binary stl. Just a type but better be fixed

### PR DESCRIPTION
**Pull request by blackhorse-reddog**
I ran into an error while processing coloured binary stl. Just a type but better be fixed

### CODE REVIEW

**Comment by turol** [comment]
This is wrong. Those bitops are for masking off specific bits. If you want them to be hex they should be `0x1f`.

**Comment by turol** [comment]
It might be better to fix them but leave them as hex like `0x1f`.

**Comment by blackhorse-reddog** [comment]
I thought about that too, and chose the decimal format to indicate it is the same 31 as the 31.0 used to construct InvVal. But you are right, there is a risk that 0x will be put in front of the number again, if it stays that way, so I rewrote it into hex.

**Review by kimkulling — APPROVED** [review]
Looks fine!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
