### PR TITLE
Prevent failing stringstream to crash the export process

### PR DESCRIPTION
**Pull request by ndotl**
Text exporters are using string streams to hold the file content first and then write them to the file in a single pass. If for whatever reason the stream has the fail bit set, tellp() will return pos_type(-1), which in turn makes the subsequent write crash - at least on Windows systems. One reason for the stream being in fail state is when its size exceeds 2^31 bytes, even on 64-bit systems (i.e., when very large scenes get exported).

The fix aborts the export with an exception if the fail bit is set on the output stream.

### CODE REVIEW

**Comment by jaredmulconry** [comment]
@ndotl Do you have a test model to reproduce the failure? This is an interesting export scenario that is worth testing.

**Comment by ndotl** [comment]
@jaredmulconry I don't have a model to share, but here is a code snippet to provoke the error:

```
        const size_t Subdivisions = 8192;

        auto outScene = std::make_unique<aiScene>();

        outScene->mNumMeshes = 1;
        outScene->mMeshes = new aiMesh*[outScene->mNumMeshes];
        outScene->mNumMaterials = 1;
        outScene->mMaterials = new aiMaterial*[outScene->mNumMaterials];

        // prepare material
        aiMaterial* material = new aiMaterial();
        const aiColor3D grey = aiColor3D(0.5);
        const float glossiness = 10.0f;
        material->AddProperty(&grey, 1, AI_MATKEY_COLOR_AMBIENT);
        material->AddProperty(&grey, 1, AI_MATKEY_COLOR_DIFFUSE);
        material->AddProperty(&grey, 1, AI_MATKEY_COLOR_SPECULAR);
        material->AddProperty(&glossiness, 1, AI_MATKEY_SHININESS);

        aiString name = aiString("mat");
        material->AddProperty(&name, AI_MATKEY_NAME);

        // create mesh
        aiMesh* meshOut = new aiMesh();
        meshOut->mPrimitiveTypes = aiPrimitiveType_TRIANGLE;
        meshOut->mName = "quad";
        meshOut->mMaterialIndex = 0;

        const float Spacing = 0.0625f;

        // create vertices
        const size_t vertexCount = (Subdivisions+1)*(Subdivisions+1);
        meshOut->mNumVertices = vertexCount;
        meshOut->mVertices = new aiVector3D[vertexCount];
        meshOut->mNormals = new aiVector3D[vertexCount];

        for (size_t i = 0, iEnd = Subdivisions, vIdx = 0; i<=iEnd; ++i) {
            for (size_t j = 0, jEnd = Subdivisions; j<=jEnd; ++j, ++vIdx) {
                meshOut->mVertices[vIdx] = aiVector3D(Spacing*i, Spacing*j, 0.0f);
                meshOut->mNormals[vIdx]  = aiVector3D(0.0f, 0.0f, 1.0f);
            }
        }

        // create faces
        meshOut->mNumFaces = Subdivisions*Subdivisions;
        meshOut->mFaces = new aiFace[meshOut->mNumFaces];

        for (size_t i = 0, iEnd = Subdivisions, fIdx = 0; i<iEnd; ++i) {
            for (size_t j = 0, jEnd = Subdivisions; j<jEnd; ++j, ++fIdx) {
                aiFace& face = meshOut->mFaces[fIdx];
                face.mNumIndices = 4;
                face.mIndices = new unsigned int[4];

                const size_t vBase = i*(Subdivisions+1) + j;
                face.mIndices[0] = vBase;
                face.mIndices[1] = vBase+1;
                face.mIndices[2] = vBase+Subdivisions+2;
                face.mIndices[3] = vBase+Subdivisions+1;
            }
        }


        // add mesh and material to Assimp scene
        outScene->mMaterials[0] = material;
        outScene->mMeshes[0] = meshOut;


        // Create node structure.
        aiNode* rootNode = new aiNode();
        rootNode->mName = "quadNode";

        rootNode->mNumMeshes = 1;
        rootNode->mMeshes = new unsigned int[rootNode->mNumMeshes];
        rootNode->mMeshes[0] = 0;

        outScene->mRootNode = rootNode;

        // export to file
        Assimp::Exporter exporter;
        const aiReturn res = exporter.Export(outScene.get(), "obj", "test.obj", 0);
```

Having a quad tessellated that much surely isn't the most sensible thing to do, but it demonstrates the issue. Play around with the Subdivisions const at the top. 4096 still works, producing a 1GB obj. 8192 makes assimp crash.

**Comment by kimkulling** [comment]
Something went wrong with travis. COuld you please try to reopen this one? I am not able to do so. Traivis will not be triggered.

**Comment by ndotl** [comment]
travis says "Abuse detected" for this PR: https://travis-ci.org/assimp/assimp/requests. No idea why. I'll send a support request to travis.

**Comment by ndotl** [comment]
@kimkulling Together with the travis support we finally sorted out the problem! Now both checks pass.

**Comment by kimkulling** [comment]
Merged, thanks for the patient and your contribution.

**Pull request merged**
