### PR TITLE
Fixing bugs related to 64-bit upgrade in materials

### PR DESCRIPTION
**Pull request by r-chris**
I found some issues with the double precision build - in particular within the material classes.

### CODE REVIEW

**Comment by r-chris** [comment]
I'll have to do some more testing before you consider merging this - I think I may have found another bug.

**Comment by acgessler** [comment]
Any update?

**Comment by r-chris** [comment]
I didn't get around to going over this again - I'll try to look at this again today to try and get it ready for merging.

**Comment by kimkulling** [comment]
Ok, great. I am looking forward to it.

**Comment by r-chris** [comment]
Had a busy day and will try over the weekend to find some time. I am seeing an export error that I couldn't find the root cause for, yet.

**Comment by kimkulling** [comment]
Take your time. There is no need to hurry and introduce more bugs :-).

**Comment by r-chris** [comment]
@kimkulling @acgessler Ok, I think I found the main problem and committed a fix. Ready when you are!

**Comment by r-chris** [comment]
Ping @kimkulling - let me know if you have the time to look at this

**Comment by kimkulling** [comment]
Thanks for the ping, merged!

**Pull request merged**
