### PR TITLE
Optimized usedVertexIndices in JoinVerticesProcess by using bitmask instead of unordered_set

### PR DESCRIPTION
**Pull request by AdamCichocki**

### CODE REVIEW

**Comment by turol** [comment]
Do you have benchmarks?

**Comment by AdamCichocki** [comment]
Cuts the JoinVertices time in half, while Join vertices take almost half the time of the whole import of models with simple vertices (i.e. no tangents etc).

**Comment by Skylion007** [comment]
Wouldn't the `std::vector<bool>` specialization be a bit more readable / helpful here? https://en.cppreference.com/w/cpp/container/vector_bool

**Comment by AdamCichocki** [comment]
@Skylion007 Fair enough, updated the PR.

**Review by Skylion007 — APPROVED** [review]

**Review by kimkulling — APPROVED** [review]
Looks fine, much better!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
