### PR TITLE
A new sample : Directx11 Textured Sample with embedded texture support

### PR DESCRIPTION
**Pull request by Ias0601**
This is a simple sample for Assimp that uses Directx11 to load and display a model.
Supports both embedded textures and non-embedded textures.

### CODE REVIEW

**Comment by Ias0601** [comment]
@kimkulling what are these tests? and why did I fail one? Won't my pull request be merged?

**Comment by kimkulling** [comment]
Great, thanks a lot!

**Comment by kimkulling** [comment]
Merged!

**Comment by Ias0601** [comment]
Thanks :)

**Pull request merged**
