### PR TITLE
Treat warnings as errors on Appveyor

### PR DESCRIPTION
**Pull request by turol**
Treat warnings as errors on Appveyor.I haven't actually tested this, let's see if it works...

### CODE REVIEW

**Comment by turol** [comment]
Looks like it isn't clean after all. Does someone have access to working Visual Studio build so they can fix that?

**Comment by jaredmulconry** [comment]
I do, though not 2013 at present.
Lemme install the dev tools for it.

**Comment by jaredmulconry** [comment]
Builds fine on 2017 toolset. Seems to be 2013-specific.

**Comment by jaredmulconry** [comment]
@turol After reading through the build logs on AppVeyor, we need to disable warning C4351 for builds on VS2013. It's a noisy warning meant for people upgrading from VS2012.

**Comment by turol** [comment]
Let's see if this does the trick. Once again, completely untested. Also we should probably add MSVC 2017 to the build matrix but that should be a separate PR.

**Comment by jaredmulconry** [comment]
Agreed. Testing on VS 2013 is difficult now, because getting VS 2013 to test locally is a chore.

**Comment by jaredmulconry** [comment]
Command line error D8021: invalid numeric argument '/Wd4351'
RIP

**Comment by turol** [comment]
Nope, looks like wrong parameter name.

**Comment by turol** [comment]
lowercase 'w', not uppercase 'W'...

**Comment by turol** [comment]
Let's try that again

**Comment by jaredmulconry** [comment]
They added the capital W for warnings levels but not for disabling them, because no.

**Comment by jaredmulconry** [comment]
Working now :)

**Comment by turol** [comment]
So far, let's see if the final build succeeds.

**Comment by turol** [comment]
Yay, passed!

**Comment by jaredmulconry** [comment]
Only issue is that it'll immediately break if we try to build the included zlib contrib :'(

**Comment by jaredmulconry** [comment]
That's the only warning I've been able to locate that hasn't been resolved.

**Comment by turol** [comment]
Well don't do that then :)

Or update the included zlib to latest and see if that fixes it.

**Comment by kimkulling** [comment]
Looks good merged.

**Pull request merged**
