### PR TITLE
[USD] Integrate "tinyusdz" project

### LINKED ISSUE #5547: [USD] Support load .usd/.usda/.usdc/.usdz models via "tinyusdz" project
### Updates
[`tinyusdz`](https://github.com/syoyo/tinyusdz) `rendermesh-refactor` branch was merged into main (`dev`) branch

### Overview
Evaluate [`tinyusdz`](https://github.com/syoyo/tinyusdz) project for feasibility

Use PR #5628 for testing

Several features are working reasonably well at least on some test models
- [x] vertices
- [x] faces
- [x] normals 
- [x] UVs
- [x] material colors
- [x] material textures
- [x] embedded textures

Partially working
- [x] blend shapes (morph meshes) detection: able to extract blendshapes in some rudimentary models

What's not working yet
- [ ] rig/bones support
- [ ] skeletal/skinned animations
- [ ] blend shape animations
- [ ] node-only animations (for testing will need USD format model similar to node-only [MotionCaptureROM.ase](https://github.com/assimp/assimp/blob/master/test/models/ASE/MotionCaptureROM.ase))
- [ ] reliable blend shape detection aside from a few rudimentary models

Other problems
- [ ] "Composition" (layered/hierarchical models) not supported yet (this means many USD models encountered "in the wild" will fail to load)

### PR DESCRIPTION
**Pull request by tellypresence**
### Overview
This PR provides limited support for loading USD model files
 - `usd`
 - `usda`
 - `usdc`
 - `usdz`

by leveraging the external `tinyusdz` project.

Closes #5547

### Details
During build a the entire `tinyusdz` repo is automatically cloned under the `contrib/tinyusdz` folder at a specific commit hash defined in `code/CMakeLists.txt`; currently the hash points to the latest commit on the main (`dev`) branch of the `tinyusdz` project.  The source code is built alongside the rest of the assimp source code and becomes part of the output library file (.a/.so etc)

### How to test this PR
- Enable CMake option `ASSIMP_BUILD_USD_IMPORTER`*

*the USD import feature has to be explicitly disabled by default.  If enabled, assimp's github CI PR automatic checks will
- clone and build the external 3rd party `tinyusdz` project code
- encounter compiler warnings
- fail the PR since there must be zero compiler warnings 

### Discussion
#1332  "Support USD," 2 Jul 2017: insightful technical discussion

### Appendix
Original PR was #5551 but got destroyed following force push due to confusion between the assimp branch named `master` and the assimp tag named `master`

### CODE REVIEW

**Comment by tellypresence** [comment]
@Christian-Prather 
Comments in issue #1332 indicate there's a lot of complexity around OpenUSD, to the point where it may not be feasible to integrate into assimp.

On the other hand, the TinyUSDZ project self-advertises as being self-contained and potentially easier to integrate:
```
TinyUSDZ is ... dependency-free... Other 3rd-party libraries included. Yes, you don't need pxrUSD/OpenUSD...!
```

**Comment by Christian-Prather** [comment]
@tellypresence 
Thank you for the response that thread was insightful. I am wondering what support if any you may need to get tinyusdz added. Looks like a lot of good progress has been made already and many of the features are there! Would love to help out.

**Comment by tellypresence** [comment]
@Christian-Prather 
Thank you for your kind words, it's good to see that someone is watching this effort closely.

Currently this PR is sort of in limbo pending resumption of work on the `rendermesh-refactor` branch of `tinyusdz`; it was proceeding rapidly through April, but hasn't been touched in a couple of months.

P.S.  It's nice of you to offer to help, do you happen to have any contacts on the `tinyusdz` project? 😉

**Comment by tellypresence** [comment]
Here's an annoyance...this PR automatically clones the `tinyusdz` repo; the clone gets done during the CI checks, and due to compiler warnings in the `tinyusdz` project code, tests
- `C/C++ CI / ubuntu-latest-g++-build-and-test`
- `C/C++ CI / windows-latest-cl.exe-build-and-test`
both fail

Think I need to disable USD feature by default so CI doesn't pull in external 3rd party code and fail the PR when it squawks.  This will be annoying to people wanting to experiment with this PR since they'll need to override the disabled CMake option to get the feature working, but oh well

## `C/C++ CI / ubuntu-latest-g++-build-and-test`
Offending file is `contrib/tinyusdz/autoclone/tinyusdz_repo-src/src/usdc-writer.cc`, screenshot attached:
ci_failing_due_to_tinyusdz_code_ubuntu_Screenshot 2024-07-11 213726

## `C/C++ CI / windows-latest-cl.exe-build-and-test`
Offending file is `contrib/tinyusdz/autoclone/tinyusdz_repo-src/src/external/stb_image.h`, screenshot attached:
ci_failing_due_to_tinyusdz_code_Screenshot 2024-07-11 213016

**Comment by kimkulling** [comment]
Lets see. Thanks a lot for your great work!!!

**Comment by dimitre** [comment]
Thank you for the great work! 
Looking forward to a new release
cc: @danoli3

**Comment by Christian-Prather** [comment]
> @Christian-Prather Thank you for your kind words, it's good to see that someone is watching this effort closely.
> 
> ~Currently this PR is sort of in limbo pending resumption of work on the `rendermesh-refactor` branch of `tinyusdz`; it was proceeding rapidly through April, but hasn't been touched in a couple of months.~ Turns out I missed that the `rendermesh-refactor` branch got merged back into `dev` (the main branch) so this PR has been updated to a recent commit of `dev`.
> 
> P.S. It's nice of you to offer to help, do you happen to have any contacts on the `tinyusdz` project? 😉

Unfortunately I do not :) but if needed happy to help out in any other way, super excited to see this merged!

**Comment by AMZN-Gene** [comment]
Excited to see this! Going to try it out in O3DE.
How are usd references handled? Example, when car.usd references tire.usd, are both file merged and flattened into one mesh?

**Pull request merged**
