### PR TITLE
Fix issue: OBJ import takes forever (#759)

### PR DESCRIPTION
**Pull request by andrewparlane**
Commit "ObjFileParser: Moved the parsing of line continuations (backslashes) … " is the main change, the other is just a minor change that was needed so that I could use ConstDataArrayIt instead of DataArrayIt.

I've tested this as best I can, but the .obj files I have are by no means extensive.

### CODE REVIEW

**Comment by kimkulling** [comment]
Sorry, but I cannot detect the better algorithm for filtering wrong lline endings. Could you please explain where this code is placed. 
And please try to separate such changed in 2 different branches. It is really hard to disdiguish between them.

**Comment by andrewparlane** [comment]
OK, so previously we have two stages.

1) \ removal
for every char in buffer
{
  if char is '\'
  {
    buffer.delete(thisChar);
    buffer.delete(newLines);
  }
}

This code was in ObjFileImporter.cpp and has been deleted. The problem with
this is std::vector::delete() has complexity O(n), and with a file with
\r\n line endings, we do 3 deletes every time we find a \.

2) parsing
while (itStart != itEnd)
{
  parseStuff();
}


Instead of doing this, I use the copyNextLine() function in
ObjFileParser.cpp. See how in the parse loop (line 137) I use
copyNextLine() to copy the next line from the data buffer into a helper
buffer. Have a look at copyNextLine(). It copies the line, but will ignore
\r or \n characters if they are proceeded by a \.

So if your .obj looked like:

v 0.000124 1.234567\
9.87654
v 123\
456\
789

The first call to copyNextLine would give:
v 0.000124 1.234567 9.87654

and the second:
v 123 456 789

It does this by simply not copying certain characters, rather than deleting
them, and since using an iterator access is O(1) and a push_back() is O(1),
then total complexity for copy of each line is O(m) where m is the line
length. Since we copy every line eventually, we have complexity O(n) where
n is the buffer length. This can be compared to the original removal of
whitespace which was O(n) to check every single character, with additional
O(n). Which gives O(n^2). You still have to parse the data in both cases,
which is character by character parsing so also O(n).

Therefore if I'm correct, the old method was either: O(n^2) or O(n log n),
and the new method is O(n).

Hope that helps to clarify why this is better, if you have more questions
just ask.

Finally, I'm not sure I understand your comment on branches? You would
prefer me to create a new branch based off master, and push my 2 commits
there, and use that as a pull request? Surely that would just be as hard to
read, since my new branch would be the same as master. I'm happy to make
modifications as needed, just let me know what you would like.

**Comment by kimkulling** [comment]
Thanks a lot! Now I got it!

**Comment by kimkulling** [comment]
Merged! Great work!

**Comment by andrewparlane** [comment]
excellent. Glad I can help.

I quit my job a few months ago and moved to Bolivia. Now that I don't spend
my days coding for work, I can actually do stuff for fun (I teach kids
circus skills).

I was hoping to do a bunch of open source stuff while out here, to bolster
my CV and what not, so I'm glad I can help out.

I don't know much about assimp ATM, but I'll probably be helping out from
time to time when something comes up.

Andy

**Pull request merged**
