### PR TITLE
Adds safety and prevents crashes for damaged files

### PR DESCRIPTION
**Pull request by DenisMikhalev**

### CODE REVIEW

**Comment by acgessler** [comment]
Very nice, thanks for doing this. The .ply file (even though it's "half") is fine to redistribute under our BSD-style license? If any other license, please put into `models-nonbsd`.

**Comment by DenisMikhalev** [comment]
@acgessler, Ply file moved to models-nonbsd dir.
I'm take ply file here http://people.sc.fsu.edu/~jburkardt/data/ply/ply.html it under LGPL license.

**Comment by acgessler** [comment]
Thanks, can you also add the license to the folder? I.e. ant-half.ply.license

**Comment by DenisMikhalev** [comment]
@acgessler, license was added.

**Pull request merged**
