### PR TITLE
Collada: added import property to disable unit size scaling

### PR DESCRIPTION
**Pull request by martinweber**
I needed the option to ignore the unit size scaling for Collada imports.

This PR adds a property `AI_CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE` which controls if the unit size scaling is applied to the root node's transform or not. It works similar to the existing `AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION` property.

The default value is false, so the behavior for Collada imports will not change unless explicitly requested.

### CODE REVIEW

**Comment by turol** [comment]
There's no need to merge master branch, we will do that when we're ready to merge. If you want to update your branch prefer rebase and force push to avoid excessive amount of merge commits.

**Comment by martinweber** [comment]
Ah sorry. I thought I hit the rebase option through the Github web interface. I will refrain from further updates.

**Comment by kimkulling** [comment]
So, I have merged the current master. Now I will start doing the code review.

**Review by kimkulling — APPROVED** [review]
Looks fine!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
