### PR TITLE
zip: Update to latest version

### LINKED ISSUE #2374: Compile failure in zip.c
```
/home/gerhardym/dev/assimp/contrib/zip/src/zip.c:51:14: error: static declaration of 'basename' follows non-static declaration
static char *basename(const char *name) {
             ^
/usr/include/string.h:486:14: note: previous declaration is here
extern char *basename (const char *__filename) __THROW __nonnull ((1));
             ^
1 error generated.
```

### LINKED ISSUE #2388: Uninitialized Variable Used bug in miniz.h
Hello,

Uninitialized variable used bug in "mz_zip_writer_add_file" function (miniz.h):
'level' variable is used before being set (at beginning of function).

"
if ((int)level_and_flags < 0)
level_and_flags = MZ_DEFAULT_LEVEL;
level = level_and_flags & 0xF;
"

This piece of code should probably be in front of the if statement

https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/util/compress/api/miniz/miniz.c

In this code the function is already fixed in this way.
But in assimp it's bugged for sure

Thanks

### PR DESCRIPTION
**Pull request by Cgettys**
Should close #2388 (may not show up due to github erroneously flagging the poster's account as a bot)
Should also close #2374

### CODE REVIEW

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging bb11f90983c866760a22f11c26717ea2cc03505d into a43ac5b3fddf576de6d1425f0c2f339b98bf0bcd - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-9cbd767e40df58a9ac97fb083ecde42099b6b720)

**fixed alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cgettys** [comment]
Not sure what to make of the CI failure honestly.

**Comment by kkulling** [comment]
Hi,

at first thanks a lot for updating this! The issues which cames up in the CI is caused by a alignment bug which could be caused by the update. I have to check.

**Comment by turol** [comment]
miniz already has code for doing the right thing, search for `MINIZ_USE_UNALIGNED_LOADS_AND_STORES`. Unfortunately it looks like it's not possible to override it from the build system, it requires changing `miniz.h`. And contrary to what the comments say, it is no longer safe with modern compilers. While the underlying architecture allows unaligned load, the compiler makes assumptions about alignment when you derefenrence a pointer. You really should always use `memcpy`, the compiler will optimize it to raw load if it's safe. Optimally this should be fixed by upstream.

**Comment by Cgettys** [comment]
I have opened a pull request with the miniz project (richgel999/miniz#124) to add a missing !defined statement to the original upstream miniz.h.
I have also opened a pull request with the zip project (kuba--/zip/#98) to add the same missing !defined to their modified miniz.h. 
However, the zip's miniz.h version is slightly out of data - someone should PR them with an update to their modified version if anyone has time, the maintainer has indicated that they'd be open to such a PR (kuba--/zip/#94).
Lastly, I'm about to figure out where we build this & define the MINIZ_USE_ALIGNED_LOADS_AND_STORES to 0 so that we can close this out.

**Comment by Cgettys** [comment]
I've updated the zip version of miniz.h to the version I created a PR for; if that PR gets modified I'll add a commit / a new PR to update miniz.h to the new version. Right now, the compile definition just forces not using unaligned access always; if someone knows how to only do so on the correct compilers, feel free to let me know, but I figured defaulting to aligned access was least likely to cause anyone with an odd compiler to have issues.
Again, if someone has time, the zip's miniz.h version is slightly out of data - someone should PR them with an update to their modified version if anyone has time, the maintainer has indicated that they'd be open to such a PR (kuba--/zip/#94).
Hopefully, the CI tests should pass now.

**Comment by Cgettys** [comment]
@kimkulling any clue why LGTM failed?

**Comment by turol** [comment]
Looks like your addition to CMakeLists.txt causes cmake to error out which then causes LGTM to fail.

**Comment by Cgettys** [comment]
Oh I'm used to new versions of cmake, forgot add_compile_definitions is new. I put in a fix that'll use the old way on old versions (can be simplified when cmake required version gets updated someday)

**Comment by Cgettys** [comment]
The direct upstream [kuba--/zip#98](https://github.com/kuba--/zip/issues/98) PR has been merged; yet again, someone could help them update the full header of miniz to the latest version if anyone's feeling awesome.

The miniz pull request is still pending, but that's two levels upstream anyway. It might be theoretically better to try to get them to change the default, but I figured that at least being able to override the default would be easier to get upstreamed & would still fix the issue.

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging 4efa3736baa522a80c2abe53d38a7b9405663c7b into a43ac5b3fddf576de6d1425f0c2f339b98bf0bcd - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-d34c2a0ac0e511a9c9e5c0f9d08b02b49496f29a)

**fixed alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cgettys** [comment]
Unfortunately Travis CI is having issues with their Linux vms right now; the analysis build is stuck in the queue. I'll check back later.

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging f653c48c23121c582890b24be9e038d41d0d8b72 into deceb4ebf49f73df48090d3c20f81ce76b89f15c - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-a0449ee90ddcf8e08cfe007600bca0975a30977c)

**fixed alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cgettys** [comment]
@kimkulling or @turol is it ok that the codacy check failed? The warnings are solely about the upstream library changes. If not, I can try to PR the upstream with improvements, since creating our own version of the library to satisfy codacy seems silly.

**Comment by kimkulling** [comment]
Hi,

I will check th codacy build to see what up there. This test is a little bit pedantic, so for me it is fine to merge your pull request. Thanks a lot lot lot for your help!

Kim

**Comment by kimkulling** [comment]
This pull request **fixes 1 alert** when merging d62724ab4f1d68702a867184b9df1430a7bd5ff8 into deceb4ebf49f73df48090d3c20f81ce76b89f15c - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-1f2ba151c43a668a2a0c62b25f55b10d26e8d50d)

**fixed alerts:**

* 1 for Comparison result is always the same

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Comment by Cgettys** [comment]
richgel999/miniz#124 has also been merged, so the changes are now fully upstream which should hopefully prevent regression :)

**Pull request merged**
