### PR TITLE
FBXMeshGeometry:  solve issue #5116 using patch provided by darktjm

### PR DESCRIPTION
**Pull request by stephengold**
This implements the fix for issue #5116 that was proposed by @darktjm on 8 September.

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]
Looks fine.

**Comment by kimkulling** [comment]
- closes https://github.com/assimp/assimp/issues/5116

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by stephengold** [comment]
Thanks, @kimkulling. I've acted as release manager for other GitHub projects and know it can get overwhelming. I encourage work at your own pace and not allow anyone to rush you. The alternative is burnout.

In my opinion, tjm's sarcastic comments at 5116 were unprofessional and uncalled for. I hope you didn't take them to heart. In my opinion, the right path is to let go of one's ego and focus on what's best for the project. In this case, that means accepting tjm's help and crediting them for it.

**Pull request merged**
