### PR TITLE
Apply modernize-use-emplace clang-tidy rule

### PR DESCRIPTION
**Pull request by Skylion007**
This PR applies the modernize-use-emplace clang-tidy rule to the code base to improve performance/readability. The clang-tidy check prefers "emplace" to "push" on STL containers when its could improve performance. 

Using emplace prevents a temporary from being constructed as the arg to push method call and instead calls the constructor of the object at the appropiate memory location within the STL container. This particularly useful for constructing objects from c_string pointers or adding std::tuple, std::pairs to containers etc since no move operation is required. This can dramatically speed up some operations involving push items onto a STL container (like a std::vector).

### CODE REVIEW

**Comment by JG-Adams** [comment]
This look like a good practice.
I wonder why this isn't taught to be used everywhere?

**Comment by turol** [comment]
You should make one commit per importer or even one per file. If this breaks something it will be very hard to bisect or revert.

**Comment by Skylion007** [comment]
> You should make one commit per importer or even one per file. If this breaks something it will be very hard to bisect or revert.

My previous static analysis PRs have been monolithic. The automated fixes are the conservative side so I really doubt they will break anything.

**Review by kimkulling — APPROVED** [review]
Looks fine.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
