### PR TITLE
[FBX] add support for multiple animations

### PR DESCRIPTION
**Pull request by VirusFree**
+ add support for multiple animations
+ change key type from uint to int (fixes bugs from negative int_t becoming a junk uint_t value )
+ detect and ignore channels with no keys in the specified take start/stop window
+ add test model with multiple animations

(for some reason github could not get the changes for #511 and got stuck, so i opened a new one)

i used boost::shared_ptr<T> for the keylist

### CODE REVIEW

**Comment by acgessler** [comment]
Thanks for updating, let's wait for Travis.

**Comment by acgessler** [comment]
I just saw the test file is ~30MiB. Assimp's entire test suite is like ~80MiB, so this is definitely a bit too large. Any chance we can shrink it or get a minimal part of it?

**Comment by VirusFree** [comment]
the test file is 34kb and it's just a box moving and spinning

**Comment by acgessler** [comment]
Mea culpa, misread the label in Github as 34000 kb. Great then :-)

**Comment by VirusFree** [comment]
yeah, i saw that too and i also thought it was 30mb so i had to go with the windows explorer to make sure it wan't :P
it's very misleading

**Comment by mwestphal** [comment]
Hi @gepa21 , what is the actual license of `test/models-nonbsd/FBX/2013_BINARY/multiple_animations_test.fbx` ?

**Pull request merged**
