### PR TITLE
Cleanup Unit Tests Output

### LINKED ISSUE #5851: Bug: Test Logs Polluting Git
Unit test log files are polluting `git status` 

**To Reproduce**
1. git clone and build assimp
2. Run the **unit** project
3. run `git status`
4. Notice that log files are polluting git
_AssimpLog_C.txt_, _AssimpLog_CPP.txt_, and more

**Expected behavior**
Log files should be ignored. 

**Suggestion**
The txt files generated should be .log files; .log files are added to the git ignore list. https://github.com/assimp/assimp/blob/master/.gitignore#L64

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AMZN-Gene**
- Cleanup unit tests that export files by making sure those files are deleted once the unit test is complete. 
- Moved logging from a .txt to a .log file so that git ignores the files
- Fixes #5851

### CODE REVIEW

**Review by moudgils — APPROVED** [review]
I am not a maintainer of this codebase but am looking forward to these change for O3DE. These changes look good to me.

**Review by kimkulling — APPROVED** [review]
Looks fine.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by AMZN-Gene** [comment]
> Merged, thanks a lot for your contribution.

My pleasure :)

**Pull request merged**
