### PR TITLE
Any interest in Rust '18 port?

### PR DESCRIPTION
**Pull request by dmgolembiowski**
Is there any desire to bring a Rust port of Assimp to the project? I'm open to re-factoring the skeleton of the package (under the port directory) if the core maintainers would prefer a different interface.
Please let me know before I start investing more time.

### CODE REVIEW

**Comment by kimkulling** [comment]
It would be really great if you could provide that!

**Comment by dmgolembiowski** [comment]
@kimkulling Great! Thanks for the opportunity!

**Comment by kimkulling** [comment]
I will!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by dmgolembiowski** [comment]
You're welcome! I genuinely look forward to taking this further!

**Pull request merged**
