### PR TITLE
Fix lgtm alerts

### PR DESCRIPTION
**Pull request by Cgettys**
Fix a number of lgtm alerts:
* port/PyAssimp/pyassimp/core.py: use correct raise RuntimeError(string) rather than deprecated/removed raise string
* Fix apparent typo in scripts/StepImporter/CppGenerator.py. @kimkulling may want to review this one - it appears to have been a typo that went uncaught in get_hierarchy because I guess that method is never called in the tests. But I could be missing something here, I didn't write the original code. I just noticed that lgtm noted an error, and the error was that a method was called with 1 argument, e.hierarchy, whereas the related methods are all called with arguments e, hierarchy
* More to come

### CODE REVIEW

**Comment by Cgettys** [comment]
TODO: rerun code generators to make sure results are the same

**Comment by kimkulling** [comment]
This pull request **fixes 21 alerts** when merging 6556a2d8ddbbc90b40b950a3ce3c4b98ba093eb9 into a43ac5b3fddf576de6d1425f0c2f339b98bf0bcd - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-779aae407d49f5d01c7fa3026c65bb8fc2cc5a8b)

**fixed alerts:**

* 6 for Unused import
* 4 for Except block handles &#39;BaseException&#39;
* 2 for Use of the return value of a procedure
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Unused named argument in formatting call
* 1 for Testing equality to None
* 1 for Illegal raise
* 1 for Comparison result is always the same
* 1 for Implicit string concatenation in a list
* 1 for Nested loops with same variable
* 1 for Wrong number of arguments in a call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kimkulling** [comment]
This pull request **fixes 20 alerts** when merging e45d120f218206cd44e3c5aa31b23096183e6c65 into 7721e430b4efac9bf86c796920885c4772399178 - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-f80020c406dc5df121c3a66b3a984976a685f92e)

**fixed alerts:**

* 6 for Unused import
* 4 for Except block handles &#39;BaseException&#39;
* 2 for Use of the return value of a procedure
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;
* 1 for Unused named argument in formatting call
* 1 for Testing equality to None
* 1 for Illegal raise
* 1 for Implicit string concatenation in a list
* 1 for Nested loops with same variable
* 1 for Wrong number of arguments in a call

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cgettys** [comment]
Think this is ready for review/merge, assuming the tests pass anyway.
* This largely gets rid of LGTM warnings.
* Reformatted a few python files in PyAssimp in the process to follow style guide
* Also fixed some miscellaneous code clarity/variable shadowing/PEP warnings along the way

Things I need help with before this can be merged:
* Rerun/ verify the output of scripts/BlenderImporter/genblenddna.py
* Rerun/ verify the output of scripts/StepImporter/CppGenerator.py
* The Pyassimp regression tests fail for me but that appears to be the case on master as well. But I thought I should note it

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Pull request merged**
