### PR TITLE
Fix Objimported supports OBJ partially specified vertex colors

### PR DESCRIPTION
**Pull request by emaame**
The omitted vertex colors are treated as (0, 0, 0, 1).
for issue #5139 

e.g

```only_a_part_of_vertexcolors.obj
v  0.0  0.0  0.0
v  0.0  0.0  1.0  0.0  0.0  0.0
v  0.0  1.0  0.0
v  1.0  0.0  0.0  1.0  0.6  0.3
```

I'm not sure that which is better (0,0,0,1) or (0,0,0,0) for omitted one.
In this patch, it is treated as (0, 0, 0, 1), the same as the next file.

```.obj
v  0.0  0.0  0.0  0.0  0.0  0,0
v  0.0  0.0  1.0  0.0  0.0  0.0
v  0.0  1.0  0.0  0.0  0.0  0,0
v  1.0  0.0  0.0  1.0  0.6  0.3
```

I'm not good at C++ now.
thanks

### CODE REVIEW

**Review by turol — CHANGES_REQUESTED** [review]
I think this is entirely the wrong approach. You should do the defaulting in the code which calls `getTwoVectors3`. It should check how many components there are and act appropriately.

**Comment by emaame** [comment]
Thank you. You are right.
The resizing before calling `getTwoVectors3` is what I needed for.

**Review by turol — CHANGES_REQUESTED** [review]

**Comment by turol** [comment]
The code is much better and simpler now. But what software actually creates files like this? Why have we not seen such before?

Need to squash these commits to make a nicer history.

**Comment by emaame** [comment]
I heard that exported from Cinema4D. but I apology I have no more information about it (version et. al).
I guess the reason is simple that vertex-color is a flavor and the most software is well mannered.

I noticed the code need to handle vertices without color at the end.
I will add a test case, and check empty and resize after getting a vector3.

I agree that `m_hasVertexColors` is not necessary, so I will remove it as well
(this member was also present in the original version, should I keep it?).

Then I will resubmit with a clean history.

**Review by kimkulling — APPROVED** [review]
Cool, great work! Thanks a lot for your help!

**Pull request merged**
