### PR TITLE
Optimized LimitBoneWeightsProcess.

### PR DESCRIPTION
**Pull request by napina**
Added SmallVector to reduce heap allocations. Simplified algorithm and removed unnecessary copying. In my testing with character with 163 bones and 40k triangles this change reduces step from 16ms to 4ms.

### CODE REVIEW

**Comment by kimkulling** [comment]
What is the advantage of adding a new class calles sall-vector, which main-content is a reimplementation of the std::vector growing strategy.

**Comment by kimkulling** [comment]
Just saw, that the inplace capacity in already in use for smaller vector data. Now I do understand it. Thanks for the great idea!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by napina** [comment]
Thanks. This technique is from https://www.youtube.com/watch?v=vElZc6zSIXM if you want to know more.

**Pull request merged**
