### PR TITLE
Editor config

### LINKED ISSUE #564: Add editor config support
As per the discussion of pull request https://github.com/assimp/assimp/pull/562, add a `.editorconfig` file to describe whitespace conventions in the codebase.  The currently proposed contents are:

````
[*.{h,hpp,c,cpp}{,.in}]
# Unix-style newlines with a newline ending every file
end_of_line = lf
insert_final_newline = true

# 4 space indentation
indent_style = space
indent_size = 4

trim_trailing_whitespace = true
````

### PR DESCRIPTION
**Pull request by LegalizeAdulthood**
Adds `.editorconfig` support and applies the following transformations to source files:

- use LF line endings
- trim trailing whitespace
- expand tabs to 4 spaces

For CMake files, I hand edited the indent to be consistent.  For C++ source files, I used `sed` and `expand`.

Closes #564

### CODE REVIEW

**Comment by acgessler** [comment]
Please do not merge yet.

**Comment by LegalizeAdulthood** [comment]
Looks like there isn't a concensus yet on whitespace.  (This pull request is only about whitespace, not overall code formatting.)

Let me know when it settles down and I'll resubmit.

**Comment by LegalizeAdulthood** [comment]
Looks like conventions settled on what I implemented, so I will update this pull request.

**Comment by acgessler** [comment]
By any chance, could you fix the merge?

**Comment by LegalizeAdulthood** [comment]
Rebased to latest.

**Comment by kimkulling** [comment]
Merged, thanks a lot!

**Pull request merged**
