### PR TITLE
Add USE_STATIC_CRT option

### PR DESCRIPTION
**Pull request by EYHN**
Allow user to choose C runtime library version, on Windows

This PR adds an option to cmake, `USE_STATIC_CRT`.

The default is OFF, which has no changes to the current build.

### CODE REVIEW

**Review by kimkulling — COMMENTED** [review]
Looks good, I will merge it!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by SirLynix** [comment]
This PR prevents building Assimp in release with /MDd or /MTd, breaking the [xmake-repo](https://github.com/xmake-io/xmake-repo) package.

```
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> assimp v5.2.3 [vs_runtime:"MDd"]
please input: y (y/n/m)
y
  => download https://github.com/assimp/assimp/archive/v5.2.3.zip .. ok
  => install assimp v5.2.3 .. failed

assimp-vc143-mt.lib(Importer.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Importer.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Version.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Version.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(BaseProcess.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(BaseProcess.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(MaterialSystem.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(MaterialSystem.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(scene.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(scene.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultLogger.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultLogger.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(ScenePreprocessor.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(ScenePreprocessor.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultIOStream.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(DefaultIOStream.obj) : error LNK2038: discordance détectée pour 'RuntimeLibrary' : la valeur 'MD_DynamicRelease' ne correspond pas à la valeur 'MDd_DynamicDebug' in _628228A2FFB8424088623A9B310E0440.o
assimp-vc143-mt.lib(Exceptional.obj) : error LNK2038: discordance détectée pour '_ITERATOR_DEBUG_LEVEL' : la valeur '0' ne correspond pas à la valeur '2' in _628228A2FFB8424088623A9B310E0440.o
if you want to get more verbose errors, please see:
  -> C:\Users\Taff\AppData\Local\.xmake\cache\packages\2203\a\assimp\v5.2.3\installdir.failed\logs\install.txt
error: install failed!
```
(sorry for the french logs).

I have to use MDd runtime because my own project uses debug (and MD libraries aren't compatibles with MDd), but don't want to compile Assimp in debug because I don't need to (and will lose a lot of performances).

I don't think this is the way thoses flags should be used. CMake already provides [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html).

If we want to keep this, we should at least provide a way to disable it to rely on standard cmake option.

**Comment by SpaceIm** [comment]
There is no reason to add this kind of option, https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html is your friend.

**Pull request merged**
