### PR TITLE
Prototype unit system for assimp

### PR DESCRIPTION
**Pull request by RevoluPowered**
This is a prototype to demo adding units of measurement into assimp.

Not intended for merge but could use testing! I have tried to remain backward compatible if you use AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY then it should still work.

This implements the following
- file based scale
- application scaling

You can now specify that you want meters by using 
- SetApplicationUnits( ImporterUnits::M );

If you have a format for example FBX and you know the scale relative to meters, please implement a call to SetFileScale( ScaleRelativeToMeters );

This will mean that if you have file scale and engine/application scale it can be factored in during the import process.

All virtual so that you can override the scaling functions too if you need some strange scaling behavior you can implement it with these calls.

**For the scaling to work out of the box:**
Your format must have called **SetFileScale(scale from meta info of file)** in the importer to take advantage of this, and I recommend the application calls Importer->SetApplicationUnits( your unit of measurement ) 

**Todo:**
- Implement Importer->SetPropertyDouble so we can use double precision.
- Test

This includes an example applied to the FBX importer.

### CODE REVIEW

**Comment by kimkulling** [comment]
This pull request **introduces 1 alert** when merging ffc19790fbe802483044c982bd35c887b614255c into bdf6612ba028e8f72113bec57a634dd41301be3d - [view on LGTM.com](https://lgtm.com/projects/g/assimp/assimp/rev/pr-f71fa039bde85f2a2478cb1411780ef05cbb286f)

**new alerts:**

* 1 for Constant return type on member

---

**Warning** - Automated code review for assimp/assimp will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by RevoluPowered** [comment]
Thanks! Sorted that now.

**Comment by kimkulling** [comment]
Looks good for me. I will implement the double-property stuff.

**Comment by RevoluPowered** [comment]
Thanks @kimkulling for sparing some time to help, it's been really good.

**Comment by kimkulling** [comment]
Merged, thanks a lot for the contribution.

**Pull request merged**
