### PR TITLE
Support basis universal to GLTF2 format

### PR DESCRIPTION
**Pull request by thomasbiang**
According to gltf2 format, images can use basis universal.
This pr is to add this support to gltf2 in assimp.

Here we support .basis and .ktx2 images in addition to the traditional png, jpg. extensionsUsed and extensionsRequired are added if there are such images.

### CODE REVIEW

**Comment by kimkulling** [comment]
Looks good so far. CI is on its way!

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by RichardTea** [comment]
@thomasbiang Is there a library you'd suggest or recommend for working with basis universal files?

**Comment by rbsheth** [comment]
@RichardTea I'm using a Hunter-forked version of https://github.com/BinomialLLC/basis_universal here https://github.com/cpp-pm/basis_universal. The fork splits out the encoding and transcoding libraries, and optionally builds the tool. Might be worth a look!

**Pull request merged**
