### PR TITLE
`build`: Add ccache support

### PR DESCRIPTION
**Pull request by ochafik**
Speeds up (re)builds with [ccache](https://ccache.dev/), if installed / detected (can disable w/ `-DASSIMP_BUILD_USE_CCACHE=0`)

```bash
rm -fR build
# First build takes a while:
cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j

rm -fR build
# Rebuild w/ same args / same content near instant:
cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j
```

### CODE REVIEW

**Comment by turol** [comment]
Why? It's much easier to either override the compiler with CMake options or override PATH environment variable to point at the ccache wrappers.

**Comment by kimkulling** [comment]
So what would you do to improve the support?

**Comment by turol** [comment]
What support needs improving? It's already possibly to use ccache with the current `CMakeLists.txt`.

**Comment by kimkulling** [comment]
You mean this feature? https://cmake.org/cmake/help/latest/envvar/CMAKE_LANG_COMPILER_LAUNCHER.html

**Comment by kimkulling** [comment]
I guess just having it implicitely shall be tested. So will merge it.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Pull request merged**
