### PR TITLE
Revert "GLTF Importer: Build a list of the actual vertices so it works well with shared attribute lists"

### PR DESCRIPTION
**Pull request by FlorianBorn71**
Reverts assimp/assimp#5003

### CODE REVIEW

**Comment by FlorianBorn71** [comment]
This PR caused a regression here:
https://github.com/assimp/assimp/issues/5084

**Comment by FlorianBorn71** [comment]
@kimkulling , please hold off  completion of this PR for a moment. I got a repro model, so I can hopefully fix the regression rather than rolling back

**Comment by FlorianBorn71** [comment]
I have a proper fix here:
https://github.com/assimp/assimp/pull/5090
If accepted, this rollback PR can be abandoned

**Comment by malytomas** [comment]
This PR should be closed without merging.
A proper fix has been merged in #5090

**Pull request closed without merging**
