### PR TITLE
closes https://github.com/assimp/assimp/issues/2228: prepare pull-req…

### PR DESCRIPTION
**Pull request by kimkulling**
…uest.

### CODE REVIEW

**Comment by kimkulling** [comment]
Looks good so far ...

**Comment by kimkulling** [comment]
DO you have some free test models for it?

**Comment by jsfrancal** [comment]
Thanks for setting this up! Yes I have some test files, what's the best way to provide them?
Actually I found a glitch in the provided OFF loader related to the way I managed the newlines, which I realized by testing one of the off test files in the assimp repository. So I updated the code in the meantime, refactored it, cleaned it up, and made it fault tolerant to typical variants seen out there. The updated implementation passes on my files and on the ones in the repository. Let me know what's the best way to provide this: should I check it all in and push it under the OFF_Importer_Redesign_js_francal branch?

Best regards,
JS

**Comment by jsfrancal** [comment]
Hi, I'm planning to push OFF examples in /test/models/OFF and a new version of the OFFLoader.cpp code which fixes endline parsing issues with the previous version, but currently in the OFF_Importer_Redesign_js_francal branch I'm getting a compilation error:

'
 [ 51%] Building CXX object code/CMakeFiles/assimp.dir/SMDLoader.cpp.o
/Users/franco/build/assimp/code/SMDLoader.cpp:126:48: error: use of undeclared identifier 'AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST'
    bLoadAnimationList = pImp->GetPropertyBool(AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST, true);
'

I'm not sure how to proceed here, I'm guessing the master branch, which probably has a fix for that, must be merged in the OFF_Importer_Redesign_js_francal branch, but I'm not sure (and I probably don't have the rights to that). What should I do ?

**Comment by jsfrancal** [comment]
Update: I just tried 'git pull' and 'git merge master' to merge the master branch in the local OFF_Importer_Redesign_js_francal branch (which is the one I'm on prior to typing these commands), which assumes a more recent version of the SMDLoader.cpp file with a fix was in the master branch, but I get 'Already up to date.'

This probably means that this SMDLoader compilation bug is in the current master with no fix.

**Pull request merged**
